### ISSUE TITLE
Remove adblock plus dependency

### ISSUE THREAD

**Issue by cooperq** [EFForg/privacybadgerchrome#119]
We should try to remove the dependency on adblock plus code. This would have several benefits such as speed, memory consumption, ease of maintainance, ease of testing, etc...

**Comment by MrAlexWeber** [comment]
+1, I suggest uBlock as the replacement: https://github.com/gorhill/uBlock

**Comment by cooperq** [comment]
I think that my plan is to remove any dependency on other adblockers entirely and do it all myself.

**Comment by cooperq** [comment]
closing this in favor of #629
