### ISSUE TITLE
Enhancement: Heuristic Data portablity

### ISSUE THREAD

**Issue by smarkwell** [EFForg/privacybadgerchrome#121]
It seems that bootstrapping an installation is a potentially long process and essentially requires exposure to 3rd parties to determine how the data is used by each installation.  While this is an excellent as far as data ownership and trust, for a person migrating between computers or even different browsers on the same computer, it would be nice to have some procedure to transfer heuristic data around that is friendly to users.  Ideally in a way that would allow merging/syncing of the information.

**Comment by cooperq** [comment]
Fixed by #982
