### ISSUE TITLE
Opera users

### ISSUE THREAD

**Issue by diracdeltas** [EFForg/privacybadgerchrome#197]
Submitted by Andreas Bovens via email:

When visiting https://www.eff.org/privacybadger with Opera, I
get an offer to download the "alpha for Chrome". Is it possible to
update this? You can recognize Opera by checking for OPR in its UA
string.

Furthermore, I take it that you'll submit Privacy Badger to
https://addons.opera.com/ as well, once it goes out of alpha? We're
happy to feature it of course.

**Comment by cooperq** [comment]
Another person asking for opera in #325 I guess we should release an opera version.

**Comment by cooperq** [comment]
We have an opera account for httpse so whoever takes this issue should test privacy badger in opera, get the credentials for the opera store and figure out if we need to do anything else to make this work. We will also need to update the website and FAQ.

**Comment by SwartzCr** [comment]
I'm curious how the update stream would work for opera, and if it means we should wait until we have a release to put it up for opera

**Comment by cooperq** [comment]
Lets wait until we have a 1.0 release for opera. Whoever takes this ticket should research how the update stream works, I assume it works the same way as the chrome one does, where we just upload a new version to the web store and everyone gets updated from the web store.

**Comment by SwartzCr** [comment]
if we're waiting for after 1.0 release to make an opera version should this be taken out of 1.0 milestones?

**Comment by cooperq** [comment]
I mean, it's not a launch blocker, but I would like to get opera out around the same time if we can. I'm going to leave it in here so it doesn't get lost.

**Comment by cooperq** [comment]
@SwartzCr bumping this. We are probably ready to put up in the opera store. We also need to update the website appropriately.

**Comment by shwetank** [comment]
Hi, I'm PM for Opera extensions. We've been getting requests from our users to have Privacy Badger on the [Opera Addons Catalog](https://addons.opera.com) - Opera and Chrome share most of the same extensions architecture. 

In fact, you can even submit the chrome .crx file as is. We'll be happy to feature it once published.

**Comment by cooperq** [comment]
Doing a chrome release today, I will test and submit an opera version as well,.

**Comment by cooperq** [comment]
@shwetank when I try to load the unpacked privacy badger in opera it fails to load and just says "errors" is there somewhere I can view what the error is?

**Comment by shwetank** [comment]
You can just click on that button which says errors and it will open up a popup listing showing the errors. 

Something like this http://imgur.com/a/heawb

(Also please let me know what version number of Opera you're using - the latest stable version is v33).

**Comment by cooperq** [comment]
weird it didn't show me that popup, (which was what I expected). I am using opera v33 - the 64 bit linux build. Strange, also I cant figure out what is causing the error. That version number seems properly formed to me. Any thoughts?

**Comment by cooperq** [comment]
oh I just looked closer at your screenshot, and I don't even get that far, badger doesn't even load, just tries and fails.

**Comment by shwetank** [comment]
@cooperq Yes, when you open it in developer mode, it gives the error. However, I can still load it, in the sense that the browser action icon displays in my dok. 

The error that I can see is the following: 

http://imgur.com/amJ23Ok

**Comment by shwetank** [comment]
I'll ask someone from our moderation team tommorow to also give it a look, in case they can catch something. :)

**Comment by shwetank** [comment]
Turns out there was a crasher bug in one of the APIs. We've fixed it, but it will be available in a future version of Opera (probably 36). I'll ping this bug once that is in a stable build.

**Comment by cooperq** [comment]
@shwetank I have finally uploaded privacy badger to the opera web store! I am just waiting for review now. Sorry this took so long, but I am committed to supporting opera from here on out! I am planning to do some publicity around this once it's available in the store. Is there any chance we could get featured?

**Comment by article10** [comment]
@cooperq Privacy Badger hasn't shown up in the Opera extensions page at addons.opera.com yet. What's the status of Privacy Badger on Opera?

**Comment by cooperq** [comment]
I submitted it but apaprently didn't do it right. I resubmitted it today and it is now waiting for approval.

**Comment by shwetank** [comment]
Its published now! https://addons.opera.com/en/extensions/details/privacy-badger/

I'll mail the email address which was used to submit the extension about further details regarding the promo image.

**Comment by cooperq** [comment]
Yes we finally published it! You can email me directly if you want or just ask quesitons here. My email is my github username @eff.org
