### ISSUE TITLE
Improvements to the first run page

### ISSUE THREAD

**Issue by cooperq** [EFForg/privacybadgerchrome#230]
The first run / onboarding page is currently a wall of text, it should have a video or some helpful images explaining what privacy badger is and how it works instead.

It should also have a link to the donation page:
https://supporters.eff.org/donate/support-privacy-badger

**Comment by cooperq** [comment]
It seems like we are considering that making a video might be the best way to do this.

**Comment by pde** [comment]
This should be open until we have a video, cartoon, or something else, right? :)

**Comment by cooperq** [comment]
Yep! I think I accidentally closed it.

**Comment by CanarySec** [comment]
@KatFrog Are you still working on this? @cooperq if not, it is essentially a landing page within the site, correct?

**Comment by cooperq** [comment]
@CanarySec we are now working on this internally (not sure what happened to @katfrog) and we are a pretty good way in on it, so I think it's covered for now. Thanks though!

**Comment by cooperq** [comment]
Fixed in #479

**Comment by gunesacar** [comment]
Slick! :+1: 
Nit: "alone ," -> "alone, " on PB-layouts-14.png.
