### ISSUE TITLE
Needs better test coverage!

### ISSUE THREAD

**Issue by cooperq** [EFForg/privacybadgerchrome#249]

**Comment by duggiefresh** [comment]
Just appending this here, since it seems relevant to this issue.

Travis isn't running the QUnit unit tests. https://travis-ci.org/EFForg/privacybadgerchrome/builds/69727700. I can look into this sometime this week.

**Comment by gunesacar** [comment]
I think it runs them. Look at the output from the [selenium/qunit_test.py](https://github.com/EFForg/privacybadgerchrome/blob/master/tests/selenium/qunit_test.py):
`QUnits tests: Failed: 0 Passed: 468 Total: 468`

**Comment by duggiefresh** [comment]
Hah! I take it back. Thanks once again for your sharp :eyes:.

**Comment by gunesacar** [comment]
You're welcome!

**Comment by cooperq** [comment]
this is still a great issue for anyone who is interested to take on. Frankly any function that does not already have one probably needs at least a unit test. I might need to set up something like a coverage tool to see where we need tests specifically.
