### ISSUE TITLE
Enhancement: 1-click config fixes for common sites

### ISSUE THREAD

**Issue by Sequoia** [EFForg/privacybadgerchrome#262]
## Scenario
I'm on youtube, I've installed PB.  It seems to work.  I want to comment, click comment box.  Popup opens then closes.  Click it again, chrome blocks popup.  Allow popups, click again.  Popup opens & closes.  Youtube appears to be trying to call to google+ or whatever for commenting.  Check privacy badger:

* apis.google.com :yellow_heart: 
* gg.google.com :red_circle: 
* plus.google.com :yellow_heart: 
* www.google.com :yellow_heart: 

Ok.... what do I do now? "I just want to comment."

## Probable outcome for many people
Disable/remove pb which is "breaking" the site, or just disable blocking willy nilly (which sort of defeats the purpose of the tool).

## Proposal
It would be nice if the pb icon blinked or something in this scenario so I could click it & be presented with "Allow youtube commenting."  These configurations would have to be tailor-made for each site/service, but I believe that a 1-click-fix on e.g. the top 10 services could alleviate 80+% of user pain around this.

**Comment by Sequoia** [comment]
Youtube.com/g+ commenting seems to have 1-click enable working! :clap: :clap: Ditto disqus! :+1: :100: Thanks

**Comment by minj** [comment]
Cannot comment on youtube without yellow->green switch for apis.google.com:
the button is disabled. Using Chrome.

![bug](http://i.imgur.com/JkzncPk.png)

**Comment by cooperq** [comment]
Making a new issue in #369
