### ISSUE TITLE
Allow upload of changes to blocking rules

### ISSUE THREAD

**Issue by bquistorff** [EFForg/privacybadgerchrome#278]
A possible enhancement to consider would be to allow users to opt-in to uploading the changes they've made to blocking rules to get get sites working. Many users probably unblock domains/cookies to get sites working without spreading that knowledge via issues here. The popular changes could then be investigated by the devs for possible code changes.

**Comment by SwartzCr** [comment]
Politically this could be a little difficult, asking users to share their usage info with us when many of them are opposed to any form of information share. There are possible ways we could implement this without it being viewed as 'tracking', for example I can imagine a link to submit feedback on the info pages.
We also want to avoid being too prescriptive with the default grey and white lists. We don't want to be the arbiters of what sites should be allowed or not, and as such we typically only greylist things that we believe don't pose a threat to non-consentual tracking.
I'm going to mark this as a feature request for a place to send common greylist additions

**Comment by cooperq** [comment]
I think that the better way to do this is via the report broken site button which we have added in 1.0 
It accomplishes the same goal of letting the devs know when a site is commonly breaking.
