### ISSUE TITLE
Gmail Compose Window Issue

### ISSUE THREAD

**Issue by johnkantorski** [EFForg/privacybadgerchrome#295]
When I open a new window in Gmail, the window "jumps" when I have Privacy Badger enabled. I took a video capture, but I can't attach it.

When I disable PB, no issue. I enable PB, issue occurs.

**Comment by SwartzCr** [comment]
Hi @johnkantorski can you post the video somewhere and attach a link? Maybe on file hoster, or post it as a gif to imgur or the like? Is the site 'just' reloading or is it a different issue.
I'm going to close this issue, if you can get back to us with more info, I'll re-open it
