### ISSUE TITLE
Stopped working in Chrome after few weeks

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerchrome#310]
After a couple weeks using Privacy Badger, all of the sudden it stopped working/allowed all cookies which were put on blocked (red), It does not seem that I can activate them again. Nothing has changed  on my computer (as far as I know that is) with regard to software, hardware etc. FYI I have windows 8 installed on the laptop and use McAfee security. 

When more information is necessary please add comment.

**Comment by grant--** [comment]
Have you by chance run ccleaner? I noticed that after running ccleaner to remove my cookies, etc. Try removing the extension and re-adding it.

**Comment by cooperq** [comment]
@cypherpunk please tell me what version of privacy badger and what version of chrome you are running. Also please list all other addons that you are running.
