### ISSUE TITLE
Chrome - Sliders not present

### ISSUE THREAD

**Issue by 1nc1n3rat0r** [EFForg/privacybadgerchrome#313]
Chrome Version: 39.0.2171.95 m

Fresh installation of Chrome with Adblock Plus and Avast plugin. When I click on the Privacy Badger icon in Chrome, the sliders for the three options are not present.

**Comment by cooperq** [comment]
@1nc1n3rat0r can you send me a screenshot?  Are you seeing domains and no sliders or just nothing at all? If you are seeing nothing at all it is probably because ABP is getting to the domains first before privacy badger has a chance to block them.

**Comment by CharlesWiltgen** [comment]
Here's a screenshot from my (current) version of Chrome:

![image](https://cloud.githubusercontent.com/assets/6807178/6770588/f3cc0458-d081-11e4-9705-01088946fe84.png)

**Comment by cooperq** [comment]
Can you visit a site I know has lots of trackers, like cnn.com and tell me what you see? Also it looks like you might have a few more addons there, can you send me a complete list of all the extensions you have installed?

**Comment by cooperq** [comment]
@CharlesWiltgen are you still having this problem? Can you answer my questions above?

**Comment by jvoosten** [comment]
Exactly the same problem here. No sliders between the text and "Disable privacy badger..." button. 
In about 99% of the cases there is no list of sites, even though there are blocked sites. One of the sites that *do* show a list is github.com (0 blocks, 6 sites listed green). Coincidence?

**Comment by cooperq** [comment]
Please do the following:

**Comment by jvoosten** [comment]
Ah... eh... I updated Chrome in the mean time (from version 39 or 40 something) to 46.0.2490.86 and now the sliders are visible. Should have told you that. But perhaps someone still has the problem and can debug it with your tips.

**Comment by cooperq** [comment]
Thanks! I'm going to chalk this up to problems with old chrome versions then.
