### ISSUE TITLE
beagleboard.org forums

### ISSUE THREAD

**Issue by PSteinberg** [EFForg/privacybadgerchrome#315]
http://beagleboard.org/Community/Forums/ does not load properly when PrivacyBadger is running.

Firefox 34.0.5
Windows 7, 64-bit

**Comment by cooperq** [comment]
moving groups.google.com to cookie blocked seems to fix the problem.  I will add it to the cookieblock list. For now I suggest you move groups.google.com to cookieblocked (yellow) manually.
