### ISSUE TITLE
Accessibility - Slider hard to see for color-blind users

### ISSUE THREAD

**Issue by desilvai** [EFForg/privacybadgerchrome#323]
The "Red", "Yellow", "Green" in the slider bar make this extension harder to use for those people with red-green color-blindness.  This is minor because of the icons at the top help someone who is color-blind figure out the correct position, however, those icons are not visible when scrolling.  

Some possible ways to improve it:
* Keep those icons visible when scrolling down a large list of potential trackers (such as a list you would see on a major news outlet like http://cnn.com, http://huffingtonpost.com, or http://foxnews.com).  
* Change from sliders to one or more status icons for each tracker (this seems like a larger change, including extensive documentation changes).  If this was the chosen approach, there could be either a single icon (harder to visually parse when skimming the list) or two "blank" circles and one "filled-in" icon.

**Comment by cooperq** [comment]
I thought I had written some code to keep the icons pinned when scrolling but I don't know what happened to it. I will write this again. Thanks!

**Comment by cooperq** [comment]
this is fixed with #397
