### ISSUE TITLE
Still no Opera version

### ISSUE THREAD

**Issue by xur86x** [EFForg/privacybadgerchrome#325]
Yes, I know this is not the repository for Opera (because it doesn't exist)
Yes, I know you'll probably hate me for rushing you.
I'll just post it here so maybe someone reads it.
Since the release of Privacy Badger I am waiting for an Opera version of the extension. I was patient, because on your site you wrote that you'd be supporting it in the "near future".
Now it's the not-so-near future and I still cannot use (the official) Privacy Badger with Opera.
I can use the .crx Privacy Badger with Opera, so it should not be much effort to check if it's working and upload it to the Opera extensions page.
Thank you.

**Comment by cooperq** [comment]
I will try to get an opera version out with the next release.

**Comment by xur86x** [comment]
Thank you very much :)
