### ISSUE TITLE
CDN blocked by PrivacyBadger

### ISSUE THREAD

**Issue by andrewpurkett** [EFForg/privacybadgerchrome#326]
When I visit www.mocavo.com the sites CDN service http://cdn2.mocavo-cdn.com is blocked, but it is not used for tracking, the site malfunctions without it

**Comment by cooperq** [comment]
You can fix this by clicking on the privacy badger icon and moving the slider for cdn2.mocavo-cdn.com from red to green.

**Comment by andrewpurkett** [comment]
Why is the default behavior to block a CDN?

**Comment by cooperq** [comment]
Interesting, looking at this closer it seems unlikely that mocavo-cdn.com should ever be blocked. Privacy badger blocks things that set high entropy cookies that show up on multiple first party domains. 

From the domain name it apperas that mocavo-cdn should only ever show up on mocavo.com. This might indicate a bug in privacy badger.

**Comment by cooperq** [comment]
unless there are other first party domains that are using mocavo-cdn to load content.

**Comment by andrewpurkett** [comment]
The only case of that is a private domain that is used as a staging server that is behind a HTTP auth barrier. If you'd like to talk in private about that more, and how to handle it, my email is my first name at my last name dot com

**Comment by andrewpurkett** [comment]
Just checked, our staging TLD is not using the CDN

**Comment by cooperq** [comment]
is it possible that blog.mocavo.com and learn.mocavo.com are using the CDN?

**Comment by andrewpurkett** [comment]
yes, but those aren't top-level-domains :)

**Comment by rossta** [comment]
Users are reporting a similar issue with our site, devpost.com. We use MaxCDN and CNAME our endpoint to assetspost.com; we don't use tracking through our CDN but we do use it load our site's image, stylesheets, and javascript assets. Any advice for troubleshooting a fix?

**Comment by Kinnera323** [comment]
@rossta . I have tried the same but the subdomains of assestsposts.com aren't blocked. I also add the screenshot here. 
![screenshot from 2015-10-28 01 21 20](https://cloud.githubusercontent.com/assets/9310107/10770692/a2929564-7d12-11e5-86ad-51aa1618fa8d.png)

**Comment by cooperq** [comment]
so again this might only be getting blocked for @rossta because you would have to go to 3 different 1st party domains that all contained assetpost.com for it to get blocked.  As for why it might be getting blocked, if the javascript being served is setting cookies or storing data in local storage it might make privacy badger think that it could be used for tracking.
