### ISSUE TITLE
Functionality appears to be broken?

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerchrome#329]
I've been using Privacy Badger since its release, and like it. I noticed today, however, that the extension's behavior seems to have changed. Normally when I change sliders on a page from green to red, once I click out of the PB window the page reloads to reflect my changes; today, however, the page does not reload and the sliders all go back to green. Help, please!

**Comment by cooperq** [comment]
Please tell me what version of chrome what version of privacy badger what site you are on and any other plug-ins you have running 

On February 9, 2015 4:27:03 PM PST, cypherpunk <notifications@github.com> wrote:
>I've been using Privacy Badger since its release, and like it. I
>noticed today, however, that the extension's behavior seems to have
>changed. Normally when I change sliders on a page from green to red,
>once I click out of the PB window the page reloads to reflect my
>changes; today, however, the page does not reload and the sliders all
>go back to green. Help, please!
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/EFForg/privacybadgerchrome/issues/329

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cypherpunk** [comment]
Chrome 40.0.2214.111 m
Privacy Badger 2014.9.16
Other extensions: LastPass 3.1.91, Google Docs 0.9, Google Chrome to Phone 2.3.3, and AdBlock Plus 1.8.10

**Comment by cooperq** [comment]
I am unable to duplicate this behavior. Have you tried restarting chrome? What page did this happen on? Also please try disabling and re-enabling privacy badger.

**Comment by cypherpunk** [comment]
I have restarted chrome multiple times, and have also disabled and renabled privacy badger. This happens on all pages. Any other ideas?

**Comment by cooperq** [comment]
What about if you disable all of your other addons? Maybe also try removing privacy badger and re installing it?

**Comment by cypherpunk** [comment]
Sorry for the delayed response. Removing and reinstalling privacy badger did the trick. 

Thanks!
