### ISSUE TITLE
Internet Archive embeds are automatically blocked

### ISSUE THREAD

**Issue by joepie91** [EFForg/privacybadgerchrome#333]
The new emulator iframe embeds from the Internet Archive appear to be getting blocked by Privacy Badger automatically. I'm not sure whether this applies to other kinds of embeds as well, or just to emulator embeds.

Example URL: http://ascii.textfiles.com/archives/4588

**Comment by SwartzCr** [comment]
Thanks for the heads up.
It seems that because the IA is using analytics cookies it's causing all 3rd party requests to the IA to be blocked. Since the IA is not an advertiser I'm happy to mark this for adding the IA to built-in greylist.
