### ISSUE TITLE
Privacy Badger blocks travis-ci.org

### ISSUE THREAD

**Issue by jleclanche** [EFForg/privacybadgerchrome#334]
Because of `travis-ci.org.ssl.fa...` being blocked (no idea what the full uri is).

eg: https://travis-ci.org/jleclanche/fireplace/builds

**Comment by cooperq** [comment]
interesting, it doesn't seem like that domain adds any cookies, so I'm not sure why it would be getting blocked. For now you can unblock it by moving the slider for that domain from red to yellow or green. I will need to look further into why this is being blocked. Do you have any cookies set from the fastly.net domain?

**Comment by jleclanche** [comment]
Nope nada.

**Comment by cooperq** [comment]
Hmm that seems like a bug to me then, I will need to look into this further.

**Comment by sayamindu** [comment]
FWIW, it looks like Privacy Badger blocks some *fastly* URLs by default. Fastly is a popular content-delivery-network used by a number of web-sites, and a lot of them (especially ones that use SSL), use a Fastly subdomain (e.g. https://travis-ci-org.global.ssl.fastly.net/) as the CDN domain name to deal with SSL certificate related issues.

Here's a screenshot, if it helps:
![image](https://cloud.githubusercontent.com/assets/163931/6365430/9aed6b2a-bc85-11e4-9b8b-dbae29175bf9.png)

**Comment by cooperq** [comment]
This makes sense. Privacy Badger is blocking fastly (and all of it's subdomains) and so travisCI's subdomain gets caught up in the mix. I don't think this is a bug. However, it does raise the question:
Should we greylist fastly?  They are a common CDN so there is some argument to unblocking them.

**Comment by jsha** [comment]
Have you figured out why fastly is blocked? Is it setting tracking cookies?

@binaryparadox, interested in taking a look at this issue? If you're not familiar with Privacy Badger, it tries to autodetect high entropy cookies as being likely trackers, and block the relevant third party URLs.

**Comment by dmccarney** [comment]
@jsha Happy to help here.

@cooperq I'm a Security Engineer with Fastly. Can you help me understand why Fastly is being blocked and what the opposition (if any) is to whitelisting our origin? Is there a practice we're undertaking that is flagging the high entropy cookie heuristics? We front a number of [open source projects](http://www.fastly.com/about/open-source/) for free that are also likely to suffer from this issue. I'd love to get this cleared up.

**Comment by cooperq** [comment]
hi @dmccarney thanks for responding. Privacy Badger blocks a third party when it sets a cookie that is seen across multiple first parties. It doesn't appear that fastly.net sets any cookies by default though does it? I'm trying to figure out how this guy got cookies set by fastly (or one of its subdomains). Is it possible that another CDN customer of fastly was serving js code which set a cookie belonging to a fastly.net domain? Or is it possible that this user got a cookie from fastly.net some other way? 

Either way I think we can at least add fastly.net to the greylist.
