### ISSUE TITLE
Add "about:blank" to a default whitelist

### ISSUE THREAD

**Issue by utkonos** [EFForg/privacybadgerchrome#335]
Privacy badger is running on the page when I load a blank tab in Chrome. This is not a network sourced page, so privacy badger is not needed. This is not a big deal until another extension called disconnect.me is also incorrectly running on this page as well. Both extensions collide and cause an extension error. This could be solved by whitelisting about:blank. Both AdBlock and Ghostery whitelist this page, so the collision is only between Privacy Badger and Disconnect.me.

**Comment by cooperq** [comment]
so, the about:blank page actually makes some third party calls, which I find interesting. I'm going to leave this alone for now.
