### ISSUE TITLE
Ubuntu, FF 36 Badger icon missing

### ISSUE THREAD

**Issue by makitso** [EFForg/privacybadgerchrome#336]
Running Ubuntu 14.04 and just updated to FF v 36 yesterday and now the Privacy Badger icon is no longer shown.  Deleted and reinstalled with no change.

**Comment by cooperq** [comment]
What version of privacy badger do you have installed? Please make sure you have the latest version from https://eff.org/pb  The version in AMO is not the latest.

**Comment by makitso** [comment]
Yes, that fixed the problem,  thanks,
