### ISSUE TITLE
Privacy Badger breaks Buffer's Chrome extension

### ISSUE THREAD

**Issue by user3** [EFForg/privacybadgerchrome#337]
Nothing happens when a user clicks on the Buffer (http://bufferapp.com) button because buffer.com and bufferapp.com are blocked.

**Comment by SwartzCr** [comment]
If you can point me at a privacy policy for buffer, we can add it to the global cookieblock list (meaning that it will only block cookies from buffer) until then you can manually fix this for yourself by selecting allow or just cookie block in the privacy badger menu (click on the privacy badger icon and move the slider to the yellow or green state for buffer)

**Comment by user3** [comment]
https://buffer.com/privacy

**Comment by jameshibbard** [comment]
Privacy Badger v2015.8.5.1 renders the Buffer Chrome extension unusable.

When I click the Buffer button, buffer.com is listed as blocked. Moving the slider to the right to allow the domain, reloads the page. When I then click the Buffer button for a second time, the domain is once again listed as blocked.

Whitelisting buffer.com has no effect.

**Comment by laurenthaug** [comment]
Same issue here, would love to see that being considered high priority as is a real issue. White listing does not work, using Buffer 25 times a week very annoying to disable extension, buffer, then re-enable. Thx!

**Comment by cooperq** [comment]
This should be fixed by the newest version 2015.8.14, please update your addons and try again.

**Comment by laurenthaug** [comment]
Excellent, thx Cooper!

**Comment by jameshibbard** [comment]
Thank you!
