### ISSUE TITLE
Privacy Badger is disabling Gizmodo.com website

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerchrome#339]
see attached sample and please fix problem...
![sample](https://cloud.githubusercontent.com/assets/97223/6432266/fa1da5a6-c018-11e4-95c4-779c2b1cb4ff.jpg)

**Comment by cooperq** [comment]
I have added kinja-static.com to the cookie block list which will fix the problem. For now the workaround is to click the privacy badger icon and  move the slider for kinja-static.com from red to yellow or green.

**Comment by SwartzCr** [comment]
Closing as this change has been made
