### ISSUE TITLE
Blocking ArcGIS Online webmaps

### ISSUE THREAD

**Issue by scw** [EFForg/privacybadgerchrome#341]
Hello,

It looks like calls to the Esri Javascript API is being flagged, see for example this page:
  http://esri.github.io/wind-js/

Setting the two domains it requests, `js.arcgis.com` and `tiles4.arcgis.com` to 'block cookies' allows the page to render fine, I think these are being falsely flagged as trackers.

Similarly, on a more [complicated page](http://www.nbcwashington.com/investigations/The-Hole-Story-294060751.html) which embeds a web map, the web map is disabled by default. In this case, these additional domains were blocked:
 - static.arcgis.com
 - tiles.arcgis.com
 - tiles2.arcgis.com
 - tiles3.arcgis.com

**Comment by cooperq** [comment]
Seems like a good candidate for adding to the cookie block list. I will do so.

**Comment by scw** [comment]
Great, thanks @cooperq!
