### ISSUE TITLE
sears.ca reviews section blocked

### ISSUE THREAD

**Issue by wmanning** [EFForg/privacybadgerchrome#342]
http://www.sears.ca.  To see reviews need api.bazaarvoice.com and display.ugc.bazaarvoice.com

Example: http://www.sears.ca/product/electrolux-30-induction-stainless-cooktop-black/622-000774190-EW30IC60LS.  This page has review that won't display without the above.

**Comment by cooperq** [comment]
I'm not comfortable adding bazaarvoice to the cookie block list since they are definitely a tracking company (see http://www.bazaarvoice.com/privacy-policy/#network_infoyousubmit). I think this is an excellent case where users can unblock it manually if they really want to.
