### ISSUE TITLE
Breaks BetterTTV extension

### ISSUE THREAD

**Issue by Stalker-Riddick** [EFForg/privacybadgerchrome#344]
Privacy badger breaks betterttv chrome extension (firefox too probably but can't check).
The extension downloads each time you load twitch from cdn.betterttv.net which is blocked it also uses api.betterttv.net, manage.betterttv.net, sockets.betterttv.net .

**Comment by cooperq** [comment]
Stalker, as a workaround you can unblock all of the *.betterttv.net domains. I am reluctant to add this domain to the cookieblock list since they don't have a privacy policy posted.

**Comment by Stalker-Riddick** [comment]
Yeah I did that, this should be their privacy policy.
https://github.com/night/BetterTTV/blob/master/privacy.html

**Comment by cooperq** [comment]
fixed in 090d4760828821114f768ff1396ac24e1db4b7dd
