### ISSUE TITLE
Privacy Badger ommits not-obviously-tracking 3rd parties from the UI

### ISSUE THREAD

**Issue by pde** [EFForg/privacybadgerchrome#345]
For instance, right now for me nytimes.com has a lot of third party videos that are hosted on cloudfront, as well as tracking code from chartbeat.net, v4.moatads.com, and serve.adfootprints.com.

None of these have cookies, though some of them are probably collecting a reading history.  Perhaps we should list all of these extra origins in a separate section below the current list of 3rd parties?

**Comment by cooperq** [comment]
We used to include all third party domains in the list and it was decided to leave them out for clarity. I agree that it would be better to include all third parties in the privacy badger UI.
I think we should go farther though and include all third parties in the same list. This would account for the fact that certain third parties may be using non-cookie-based tracking methods, such as fingerprinting.   
Or we could compromise and include any third party domains that have been seen on multiple first party domains. This would prevent single domain CDNs and such from showing up on the list, which might be preferable.

**Comment by pde** [comment]
If we implement this, we should put all of these domains in a separate section of the list, *below* all of the trackers, perhaps with a line of text to explain what they are.

**Comment by cooperq** [comment]
fixed as of 73e397d9bed5bbe66ab3243d9d40ac26b5807e72
