### ISSUE TITLE
Prevents loading of images after some running time even when disabled for the site

### ISSUE THREAD

**Issue by ewirch** [EFForg/privacybadgerchrome#347]
We have a Jira instance running in our local network. I disabled PB for this domain. I keep Chrome open for several days usually. And I have a pined tab which always shows the dashboard of our Jira instance. After one or two days of run time the images stop loading for this tab. The images are listed as "(pending)" in the Network tab of Developer Tools. Refreshing the tab does not help. Opening the same url in a different tab loads correctly.

I disabled all extensions except PB to make sure PB is the culprit. Disabling PB as well makes the problem go away.

OS: Windows 7
Chrome: 41.0.2272.101 m (64-bit)
PB:  2014.9.16

**Comment by ewirch** [comment]
Buggy behavior still present in 2015.8.5.1.

**Comment by ewirch** [comment]
Problem did not appear for several days now using 2016.5.24.

**Comment by cooperq** [comment]
Great! Glad it was fixed :)
