### ISSUE TITLE
Crashes Chrome on Trello

### ISSUE THREAD

**Issue by lusi8559** [EFForg/privacybadgerchrome#348]
When I access Trello in incognito mode with the plugin initialized, my browser crashes. I am using chrome 41.0.2272.101 (64-bit) on Linux op 3.16.0-33-generic #44-Ubuntu SMP Thu Mar 12 12:19:35 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux.

**Comment by cooperq** [comment]
I am unable to reproduce this. Do you have any other addons running? If you open trello in normal browsing mode does the browser still crash? Does it crash instantly or does it crash after a few minutes? For now as a workaround you can disable privacy badger on trello.com by clicking the icon and clicking disable on this site.

**Comment by cooperq** [comment]
Also does it crash your whole browser or just the trello tab? Does it crash any other sites?

**Comment by lusi8559** [comment]
Upon further inspection, I learned that this is a driver issue. I misattributed this bug to privacy badger; sorry about that. Please close this issue.
