### ISSUE TITLE
licensebuttons.net blocked

### ISSUE THREAD

**Issue by gcochard** [EFForg/privacybadgerchrome#349]
When attempting to load http://spec.commonmark.org/ I get a broken image for the CreativeCommons badge. This image is loaded from `https://licensebuttons.net/l/by-sa/4.0/80x15.png`. Should this domain be blocked entirely?

**Comment by cooperq** [comment]
This should certainly not be blocked! I am adding this to the greylist now.

**Comment by cooperq** [comment]
fixed in 3f57cafb3f38285514839ab76cce5ced352942ec

**Comment by gcochard** [comment]
Thanks!
