### ISSUE TITLE
PB 0.2.6 preventing Mail.com page rendering since 3/31/15

### ISSUE THREAD

**Issue by bill-as** [EFForg/privacybadgerchrome#354]
Around 3/31/15 Mail.com changed their home page such that it will no longer render fully in HTML using Firefox with PB 0.2.6 active. The entire header and intro sections ate rendered only in plain text, and the hyperlinks don't resolve.
Removing all the possible PB options does not correct the issue.

**Comment by bill-as** [comment]
Issue appears confined to Win XP OS - Win 7 w/ Firefox in identical configuration rendered normally.

**Comment by cooperq** [comment]
Can you send me a screenshot of the page with the privacy badger menu open so we can see which domains are being blocked?

**Comment by bill-as** [comment]
Here you go, Quentin....
As a reminder, this is the unrendered mailbox page; the 
login page behaves the same way.  I wasn't able to 
selectively disable the domains being blocked, so couldn't 
see if one of these is definitely the culprit. The two 
German domains are being allowed; only the uicdn domain is 
being blocked, and it shouldn't be involved in page 
rendering processes.


---tried to update this on the bug report page but don't 
think it succeeded.

-- 

Thanks!
Bill Sullivan
(510) 793-4615

**Comment by cooperq** [comment]
Unfortunately the image didn't make it through, can you try again? When you say you couldn't selectively disable certian domains what do you mean by that? What happens when you try to move them from red to green?

**Comment by bill-as** [comment]
Cooper;
At your suggestion I found a way to clear the block settings 
(slider that doesn't look like one?) and found that two 
sites were causing the problem (on different pages):
s.uicdn.com
sec-s.uicdn.com

Since doing so, the issue has not recurred.
I appreciate your help!

-- 

Thanks!
Bill Sullivan
(510) 793-4615

**Comment by cooperq** [comment]
great! I will add uicdn.com to the cookie block list so this doesn't happen again.
