### ISSUE TITLE
Make UI nicer

### ISSUE THREAD

**Issue by SwartzCr** [EFForg/privacybadgerchrome#361]
The pop-up and menu UI should be nicer looking!

**Comment by cooperq** [comment]
Specifically the following:
* replace options text with gear icon
* center key icons
* key icons should float at top
* better link explaining tracker
* link back to onboarding
* prettier buttons
* nicer popup

**Comment by cooperq** [comment]
fixed as of ba7236dcda922172c2d0f108413641cacd90f34a
