### ISSUE TITLE
fingerprint and supercookie blocking for things on the yellow list

### ISSUE THREAD

**Issue by cooperq** [EFForg/privacybadgerchrome#366]
Maybe we can do this through JS monkeypatching and NPAPI magic for flash or by making all plugins click to play.

**Comment by pde** [comment]
Probably this should be two separate tickets, or even three, since HTML5 will be easier than Flash will be easier than fingerprinting?

**Comment by alexristich** [comment]
As discussed, this issue is too non-specific, and can be better addressed with multiple issues each regarding a specific detection/defense. As such, I'll go ahead and close this issue.
