### ISSUE TITLE
Raw HTML in menu

### ISSUE THREAD

**Issue by plsql** [EFForg/privacybadgerchrome#371]
I saw this when visiting bankofamerica.com's homepage:
```
Detected 2 <a id='trackerLink' target=_blank tabindex=-1 title='What is a tracker?' href='https://www.eff.org/privacybadger#trackers'>trackers</a> from these sites:
```
It was where I would have expected that message to be, and wasn't a duplicate.

I'm using NoScript, which may be related. However, I didn't see an entry for Privacy Badger in the NoScript drop-down.

**Comment by SwartzCr** [comment]
odd
the menu rendering script is pretty hacky, has this happened to you on other sites as well? Do you think you could look at the console (right click, inspect element, select console) and share any errors you see there?

**Comment by plsql** [comment]
This is the first time I've noticed it. I actually can't reproduce it now, so this bug should probably just be warehoused and used as motivation for eventual refactoring of the menu rendering script (IMHO).

I should also mention that I'm on OpenBSD, which is probably non-standard. It's Firefox 27.0.1, though, and is a pretty lightly patched build.

**Comment by SwartzCr** [comment]
cool, we are already planning to re-do a lot of the menu bar code. I'm going to close this issue for now, feel free to open a new one if it happens again and you can provide more info.
