### ISSUE TITLE
Privacy Badger default settings make Schwab index fund prospectus site unusable

### ISSUE THREAD

**Issue by orborde** [EFForg/privacybadgerchrome#372]
With Privacy Badger enabled in Chrome, the useful page content fails to load at the following URL (and many others on the same domain):

https://www.schwab.com/public/schwab/investing/investment_help/investment_research/mutual_fund_research/mutual_funds.html?&&path=%2FProspect%2FResearch%2Fmutualfunds%2Fsummary.asp%3Fsymbol%3DSWPPX

**Comment by orborde** [comment]
I'm guessing it's just that some or all of the domains this site loads should be whitelisted, but I'll leave it to someone else to work out precisely which.

**Comment by cooperq** [comment]
looks like unblocking www.schwab.wallst.com fixes the problem. I will add wallst.com to the cookie block list.
