### ISSUE TITLE
Unable to download images from Google Drive when enabled

### ISSUE THREAD

**Issue by Hans-Brakeley** [EFForg/privacybadgerchrome#377]
With Privacy Badger running, I am now unable to download images from google drive. Other document types seem to work fine still.

**Comment by cooperq** [comment]
I just tested this and chrome blocked a popup when I tried to download an image from google drive (with or without privacy badger enabled). Allowing popups for google drive fixed the problem. Does this fix it for you? If so this is not a privacy badger bug but just an annoyance in the way popup blocking in the browser works.

**Comment by Hans-Brakeley** [comment]
That doesn't seem to be my problem. I've got popups blocked and can still download images without any issue. But once I turn on privacy badger all I get is a quick "scanning for viruses" and then nothing happens, regardless of cache clearing etc.

Separate note, it's interesting that chrome would block downloads from their own site as a popup for you..

**Comment by cooperq** [comment]
@Hans-Brakeley can you send me a screenshot of the privacy badger menu when you try to open an image from google drive? I want to see which domain is blocked.

**Comment by Hans-Brakeley** [comment]
![drive_image_issue_cause](https://cloud.githubusercontent.com/assets/4742282/8009146/97678a06-0b74-11e5-9e5b-989cf367e628.jpg)

That's one that needs to be toggled to allow the download. For each different image a similar 'tracker' will show up in the list. It doesn't show up until you've tried downloading once, then it gets added and you can toggle it and download the file. Other filetypes are handled differently, and no tracker needs to be allowed it seems.

**Comment by buren** [comment]
@Hans-Brakeley +1 had troubles with downloading files from google drive as well whiteslisting: `doc-04-98-docs.googleuserco...` worked for me too.

**Comment by cooperq** [comment]
I have added a one click whitelist exception for this domain. This should fix the problem for future users.

**Comment by diego898** [comment]
Hm. I cant seem to download ppt files from google drive. It works when I disable the extension however.
