### ISSUE TITLE
Whitelist request for omroep.nl

### ISSUE THREAD

**Issue by heinhuiz** [EFForg/privacybadgerchrome#378]
omroep.nl is the content provider for the Dutch public television. The Netherlands uses a rather unique system of public broadcasting. Public-broadcasting associations are allocated money and time to broadcast their programmes on the publicly owned television and radio channels. All broadcasters have their own websites (like kro.nl, vara.nl, eo.nl, vpro.nl) and there is a site for the umbrella organisation, npo.nl. These all use the resources of omroep.nl, especially the video player at npoplayer.omroep.nl for video on demand services. Because all the broadcasters use this player, it gets blocked by Privacy Badger. Please put omroep.nl on your whitelist.

**Comment by cooperq** [comment]
Thanks for bringing this to our attention omroep.nl has been added to the cookie block list
