### ISSUE TITLE
YouTube notifications list says I'm logged off

### ISSUE THREAD

**Issue by Olathe** [EFForg/privacybadgerchrome#387]
I can't see the YouTube notifications list when Privacy Badger is on.

0. Go to YouTube
0. Sign in
0. Click on your account picture in the upper right, see that it knows you're logged in.
![account picture](https://cloud.githubusercontent.com/assets/412242/7693251/b43463ce-fd9c-11e4-8b3a-6dd75afcc6f7.png)
0. Click on the notifications list (bell) in the upper right, see that it asks you to sign in.
![notifications list](https://cloud.githubusercontent.com/assets/412242/7693255/c1805056-fd9c-11e4-8753-f08b804a078e.png)

**Comment by cooperq** [comment]
it seems like setting privacy badger to allow plus.google.com fixes this problem. This is probably worth adding a one click fix popup for.

**Comment by terrorist96** [comment]
@cooperq @SwartzCr I am experiencing this exact issue all of a sudden. It worked fine previously. Now, I have to move plus.google.com from yellow to green in order to use the notification bell.

**Comment by cooperq** [comment]
This should be fixed by #841 and in the newest release which was out this morning.
