### ISSUE TITLE
Write brief policy guidelines for the grey/cookieblock/yellowlist

### ISSUE THREAD

**Issue by pde** [EFForg/privacybadgerchrome#399]
We should try to document the factors that are considered for yellowlist inclusion.

**Comment by pde** [comment]
Some of them:
* Was this in [Bau and Mayer's](https://jonathanmayer.org/papers_data/bau13.pdf) manually curated non-tracker list? @jonathanmayer @jbau
* Is this domain necessary for functionality the user expects from 1st party pages?
* Is the domain's privacy policy clear that it does not perform non-consensual tracking?

**Comment by pde** [comment]
* If the domain is "necessary" for functionality, is there a static surrogate available, per #400?

**Comment by cooperq** [comment]
@pde perhaps you and I should work on this together.

**Comment by cooperq** [comment]
This has been added to the repo.
