### ISSUE TITLE
social widget replacement double blocks certain widgets

### ISSUE THREAD

**Issue by SwartzCr** [EFForg/privacybadgerchrome#402]
go to: http://www.gamasutra.com/blogs/LarsDoucet/20131203/206159/On_Procedural_Death_Labyrinths.php
and notice two blocked google plus icons.
disable privacy badger and notice that there is only one google plus share button
when there should only be one replaced icon in the first place

**Comment by gunesacar** [comment]
This is probably due to my [PR about social widgets](https://github.com/EFForg/privacybadgerchrome/pull/395/files#diff-a7e3669d2b1a8fab33514e1059d4cc30R77). Let me look into this.

**Comment by SwartzCr** [comment]
fixed in #403
