### ISSUE TITLE
Number of tracking domains no longer appearing on PB icon

### ISSUE THREAD

**Issue by SwartzCr** [EFForg/privacybadgerchrome#406]
The number of tracking domains on a given site is no longer appearing on the privacy badger icon. Previously it would be a green 0 or a red number with the number of tracking domains. It's possible this was broken in #396 in an attempt to fix some of the error reporting that was flooding the console.
CC @gunesacar

**Comment by SwartzCr** [comment]
This is an error with lines 728-731 of background.js
frames[tabId] always returns undefined causing the following code to never execute, never loading the images.
I commented out those lines and now numbers are displaying as usual again, I'm going to find the correct method for checking if a tab still exists (since frames[id] doesn't work)

**Comment by SwartzCr** [comment]
Upon further inspection, even with multiple try catches the error that is getting thrown is coming from the belly of chrome's sendRequest, so I'm inclined to fix this and deal with intermittent errors appearing in the console
Unchecked runtime.lastError while running tabs.get: No tab with id: 285.
    at updateCount (chrome-extension://ifbedbjeapflabhmfemlepnkcafcaigc/src/background.js:729:17)reportIfUnchecked @ extensions::lastError:133handleResponse @ extensions::sendRequest:79

**Comment by SwartzCr** [comment]
Fix can be found here: https://github.com/EFForg/privacybadgerchrome/commit/f98b266930e87bd098370e3bf8ba747eec1a46ee
@cooperq or @gunesacar can you look at this code and if so we can commit it to master
(don't make a PR as I think that branch is fubar'd)

**Comment by gunesacar** [comment]
@SwartzCr I wouldn't be able to test now but maybe the [try-catch statement](https://github.com/EFForg/privacybadgerchrome/commit/f98b266930e87bd098370e3bf8ba747eec1a46ee#diff-961641dd6af66f5e3313307cf4eb8f1dR737) (introduced in my commit) can be removed. I also observed that it can't catch the exception we try to deal with. Thanks for fixing this!

**Comment by cooperq** [comment]
Let me take a look at this one, I think I have an idea of whats going on
here.

**Comment by SwartzCr** [comment]
This fixes some of the errors, but we are still getting a good deal, as seen here http://paste.debian.net/195701/
 so let's leave this open
