### ISSUE TITLE
Cookieblocklist changes are not being deployed

### ISSUE THREAD

**Issue by pde** [EFForg/privacybadgerchrome#419]
For instance, #412 is still [not live](https://www.eff.org/files/cookieblocklist.txt)!

**Comment by cooperq** [comment]
I have pushed it as of now, but the real solution here is to automate this in some fashion.

**Comment by SwartzCr** [comment]
this may be related to the date issue in #443 
We should take a look at the code that sets the _lastUpdate date

**Comment by SwartzCr** [comment]
looks like this was addressed in #466 and #457

**Comment by cooperq** [comment]
This is not a bug, it is an issue about automatically uploading cookieblocklist changes to the EFF server. Just needs some tooling written. Leaving it open but this isn't a launch blocker.

**Comment by cooperq** [comment]
I added a pre-push hook to my repo to automatically upload cookie block list changes. @SwartzCr, you should do the same, I will share my script with you.
