### ISSUE TITLE
Update Facebook Share image

### ISSUE THREAD

**Issue by gunesacar** [EFForg/privacybadgerchrome#421]
Privacy Badger needs a replacement image for Facebook Share social widget. The [current image](https://github.com/EFForg/privacybadgerchrome/commit/70cd1b4c4676441a901b0a7cff7246661702f7bb)  has been added as a temporary placeholder and is a copy of Facebook Like button. This may cause some confusion.

**Comment by SwartzCr** [comment]
happy to help if anyone could figure out where to get an SVG of the share button.
embed code is here: https://developers.facebook.com/docs/plugins/share-button

**Comment by anirvan** [comment]
@SwartzCr, as a start, here's an SVG/CSS implementation of a basic Facebook share button:

http://www.mattboldt.com/demos/social-buttons/
