### ISSUE TITLE
Update Privacy badger website

### ISSUE THREAD

**Issue by cooperq** [EFForg/privacybadgerchrome#424]
Use designs from hugh.  consider using https://github.com/heiseonline/shariff

**Comment by CanarySec** [comment]
This sounds like something I might like to help with...

**Comment by cooperq** [comment]
I appreciate the offer to help! However this is something that we, once again, have already started in house and will be setting up in Drupal. 

Please don't be discouraged though, I appreciate your eagerness to contribute to Privacy Badger! Let me see if I can find another issue that would be good for you. I have marked a few as 'Good volunteer task' do any of those sound fun to you?

**Comment by cooperq** [comment]
Done!

**Comment by CanarySec** [comment]
Right now, none of those match my current skill level. Definitely shoot a line if something comes up. :)

**Comment by cooperq** [comment]
Keep looking @CanarySec! There are also lots of open issues not in the 1.0 milestone that might be at your skill level. Thanks for being enthusiastic!

**Comment by CanarySec** [comment]
@cooperq Definitely... we all gotta start somewhere, and I am very stubborn. :) Thanks for the encouragement!
