### ISSUE TITLE
Add comments to code

### ISSUE THREAD

**Issue by Thorsten-Sick** [EFForg/privacybadgerchrome#428]
If you want I can add comments to function headers throughout the JS code. Would be a good task to get started for me and make it more simple for others to join the project.

**Comment by cooperq** [comment]
That would be fantastic, and a huge help! We have a style guide for the firefox version here: https://github.com/EFForg/privacybadgerfirefox/blob/master/doc/style.md
If you wanted to add comments and fix style nits in general that would be amazing!

**Comment by Thorsten-Sick** [comment]
I am currently adding the comments. Leaving the style fixes alone. This PR will already have enough lines....
I think opening a new issue for the style fixes would be better

**Comment by cooperq** [comment]
:+1:
