### ISSUE TITLE
usercontent is getting blocked

### ISSUE THREAD

**Issue by SwartzCr** [EFForg/privacybadgerchrome#435]
in my field reporting branch usercontent (like abc.googleusercontent.com and abc.githubusercontent.com) were getting blocked. I'm worried that this might have something to do with the new supercookie and canvas detection
In the popup it showed that I could revert control of these things, but when I went to my options page and checked the blacklists manually nothing for these origins was there. That is also concerning.
I've switched to master and it doesn't seem to have persisted but, I'm going to keep an eye out for this happening again

**Comment by mlane3** [comment]
Hey SwartzCr, so I know nothing about Privacy Badger innerworkings and I am not a computer programmer.  Your comment did remind me of this article http://blog.kerika.com/googleusercontent-com-can-trip-you-up-if-you-disable-third-party-cookies/ and this article
Googleusercontent has been known to sometimes use 3rd party cookies.  So maybe the issue might be deeper?

P.S. This was the closest I could find about googleusercontent.com and supercookies: http://mathbabe.org/2013/04/25/whos-tracking-the-trackers/

**Comment by cooperq** [comment]
This seems like it was maybe a fluke so I'm gonna close it for now. We will re open it if this happens again.
