### ISSUE TITLE
Warning when installing Privacy Badger

### ISSUE THREAD

**Issue by adikamdar** [EFForg/privacybadgerchrome#437]
Got this warning after I loaded the extension:

There were warnings when trying to install this extension:
This extension includes the key file '/Users/adi/privacybadgerchrome/scripts/dummy-chromium.pem'. You probably don't want to do that.

![screenshot 2015-06-22 17 44 57](https://cloud.githubusercontent.com/assets/1112044/8296531/7e645dbe-1906-11e5-94ef-fd7be5fd0588.png)

**Comment by cooperq** [comment]
this is expected due to the fact that you are running a version in development. Won't be a problem in the released version.
