### ISSUE TITLE
Supercookie detection bypasses whitelist

### ISSUE THREAD

**Issue by SwartzCr** [EFForg/privacybadgerchrome#441]
![screenshot 2015-06-23 17 11 43](https://cloud.githubusercontent.com/assets/649860/8320147/fef2ec50-19cb-11e5-8714-fdb18e3275b3.png)
![screenshot 2015-06-23 17 12 03](https://cloud.githubusercontent.com/assets/649860/8320148/ff04d802-19cb-11e5-9991-a01547773fa2.png)
Here google is marked as having its super cookie detected and is blocked, even though it is on the whitelist

**Comment by cooperq** [comment]
www.google.com is on the whitelist, google.com is not. Are there other examples of this?
