### ISSUE TITLE
figure out how to display an overridden eTLD+1

### ISSUE THREAD

**Issue by cooperq** [EFForg/privacybadgerchrome#447]
When users make an override on the options page, they override teh settings for the ETLD+1. This can be confusing because in the popup the fqdn is shown but cant be undone because the rule is for the ETLD.  There are two possible solutions for this.

1. Better but harder:  display the etld at the top and the fqdns slightly indented under it. ETLD gets the undo button, fqdns do not. 
2. Easier but worse UI: grey out the undo button for an fqdn whos tld is overridden, explain in the rollover text.

If you are taking this issue it is up to you which way you want to implement it.

**Comment by SwartzCr** [comment]
made a PR for this in #476 there's a decision that should be made on how things are displayed, but this at least provides the functionality

At some point this should be built in with get action, but as that's now in adblock land this is a monkey patch on top of the pop-up code

**Comment by cooperq** [comment]
#476 has been merged!
