### ISSUE TITLE
Remove redundant code for enable/disable PB button

### ISSUE THREAD

**Issue by gunesacar** [EFForg/privacybadgerchrome#451]
Just wanted make sure the removal of the global activate/deactivate button was really intended.
https://github.com/EFForg/privacybadgerchrome/commit/95389ff624afe6a79cb2e1fcf133e50aaa005741?diff=unified#diff-35d5edd104e75ba18322956e54076412L54

Then maybe the event handlers and other related code could also be removed:
https://github.com/EFForg/privacybadgerchrome/blob/0a8eff761fcc201ce8105ebed38e5f793b4c81f3/src/popup.js#L155

**Comment by cooperq** [comment]
That was purpousfully deleted. It is redundant with disabling the addon from chrome://extensions and I didn't feel it was needed. I agree the event handlers could be removed.

**Comment by gunesacar** [comment]
Great! Updated the issue title.
