### ISSUE TITLE
Styling for report error popup

### ISSUE THREAD

**Issue by cooperq** [EFForg/privacybadgerchrome#452]
It's pretty basic and ugly right now, we should style it and also give some indicator of success and a fade out when the user hits the submit button. We should also answer this open question:
Do users expect to recieve communication since we are encouraging them to post a message?

**Comment by SwartzCr** [comment]
relevant code is at:
https://github.com/EFForg/privacybadgerchrome/blob/master/skin/popup.html#L35-L40
https://github.com/EFForg/privacybadgerchrome/blob/master/src/popup.js#L76-L86

**Comment by cooperq** [comment]
see EFForg/privacybadgerfirefox#399 for suggestions.

**Comment by taravancil** [comment]
I'm working on this :)

**Comment by cooperq** [comment]
Yay! Thats awesome, thank you :+1:

**Comment by SwartzCr** [comment]
looks like this was solved in #469 
closing!
