### ISSUE TITLE
web.skype.com needs a domain adding to the whitelist to work

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerchrome#455]
Trying to use privacy badger in Firefox to access https://web.skype.com/en/

I needed to change slider setting for domain client-s.gateway.mess...live.com from completely blocked (red) to whitelisted (yellow) or no conversations can be viewed

Apologies for the ellipsis that's as much of the domain as I can find

Probably a bit silly using privacy tools with a web based version of Skype I know

**Comment by SwartzCr** [comment]
It seems to be messages.live.com who's privacy policy can be found here: https://www.microsoft.com/en-us/servicesagreement/
It seems like this should be whitelisted, as it's only being used as part of microsoft services that have other binding policies

**Comment by SwartzCr** [comment]
sorry, messanger.live.com

**Comment by SwartzCr** [comment]
fixed in #510
