### ISSUE TITLE
white list request: tcache.sbgnet.com

### ISSUE THREAD

**Issue by chip-rosenthal** [EFForg/privacybadgerchrome#461]
I needed to override tcache.sbgnet.com (red -> yellow) to view http://www.keyetv.com/

**Comment by SwartzCr** [comment]
hi @chip-rosenthal, I see the same problem, but I don't see tcache.sbgnet.com setting cookies for me, which means that Privacy Badger won't block it. I also can't find any information on how sbgnet handles user's information. As per our yellowlist criteria (https://github.com/EFForg/privacybadgerchrome/blob/master/yellowlist-criteria.txt) this makes me reluctant to add them to our central domain exception list.
I'm going to close this ticket, but if you can provide me with either a privacy policy by sbgnet or a way to test having that resource get blocked by privacy badger I'm happy to work to get it onto the list. Until then I suggest you just do this override personally.

**Comment by chip-rosenthal** [comment]
Thanks @SwartzCr 

Looking deeper, it appears that no cookies are coming from sbgnet.com, but there are some critical page elements (CSS and JS) fetched from tcache.sbgnet.com.

Using the "Developer Tools" in Google Chrome, here is what I see when I look at one of the requests:

  General:
    Remote Address:174.127.81.162:80
    Request URL:http://tcache.sbgnet.com/template/news_js/jquery.min.js
    Request Method:GET
    Status Code:200 OK

  Request Headers:
    Accept:*/*
    Accept-Encoding:gzip, deflate, sdch
    Accept-Language:en-US,en;q=0.8
    Cache-Control:no-cache
    Connection:keep-alive
    DNT:1
    Host:tcache.sbgnet.com
    Pragma:no-cache
    User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.15 Safari/537.36

  Response Headers:
    Accept-Ranges:bytes
    Age:691
    Connection:keep-alive
    Content-Encoding:gzip
    Content-Length:33424
    Content-Type:application/x-javascript; charset=UTF-8
    Date:Sat, 01 Aug 2015 03:35:32 GMT
    host:tcache.sbgnet.com
    Last-Modified:Thu, 02 May 2013 16:15:37 GMT
    Server:nginx/1.0.15
    Via:1.0 hq-ded-proxy-1.sbgnet.com (squid/3.1.10)
    Via:1.1 varnish
    X-Cache:HIT
    X-Cache-Hits:4
    X-Cache-Lookup:HIT from hq-ded-proxy-1.sbgnet.com:8060
    X-Cacheable:YES
    X-Life:90.000
    X-Loc:tcache
    X-Varnish:3174150210 3174122929

As you can see, no cookies, just a straight up HTTP request.

There were six different requests to tcache.sbgnet.com, none of them had any cookies in the request or response headers.

So, why is Privacy Badger blocking these request? They just look like a CDN that Sinclair Broadcasting setup for their sites. (If so, I'd expect this would impact a LOT of TV station websites, not just the one in Austin.)
