### ISSUE TITLE
Design doc is not clear on yellowlist structure

### ISSUE THREAD

**Issue by pde** [EFForg/privacybadgerchrome#470]
Is the yellowlist made of eTLD+1s? FQDNs? ABP filter list entries?  How does it interact with the heuristic accounting data structure?

**Comment by cooperq** [comment]
My understanding is that the cookie block list is made of FQDNs. Where any FQDN in the list and any subdomains of that FQDN should be cookie blocked instead of full blocked.

**Comment by cooperq** [comment]
@SwartzCr do you agree?

**Comment by cooperq** [comment]
Oh and also they are formatted like abp filter entries, but honestly that should probably change.
