### ISSUE TITLE
Humorous errors

### ISSUE THREAD

**Issue by mlane3** [EFForg/privacybadgerchrome#472]
So I know you guys work tirelessly to fix privacy badger, so I thought I would share with you some humorous errors that found in my log while posting pictures for @SwartzCr .
List of Funny completely unrelated pictures:

So apparently this happens if you never turn off background after months of debugging:
![image](https://cloud.githubusercontent.com/assets/1785885/8639526/a2df44fc-28aa-11e5-9b0b-2a2eaee040b3.png)
I would think the memory space of the error log would overload at some point.

And this happens if you force+quit tabs after opening them too quickly:
![image](https://cloud.githubusercontent.com/assets/1785885/8639528/aa726320-28aa-11e5-8355-4ce4a752a834.png)
Well yes Privacy Badger you cannot find a tab if that tab has already be closed.

**Comment by SwartzCr** [comment]
I'm not sure that that first one is really 'our' issue, so I'm not worried about it.
The second one is a pain, that we've managed to cut down a lot of it's output. At this point it seems manageable but still a nuisance.
I'm going to close this issue just for sanity sake as we have a lot of things to work on, but if you notice a lot of that second error please do open up a new issue so we can try to diagnose what is still getting through.
