### ISSUE TITLE
SeaMonkey support

### ISSUE THREAD

**Issue by mylittleplaceholder** [EFForg/privacybadgerchrome#482]
Privacy Badger won't install in SeaMonkey (the sister of Firefox). It will install if converted at http://addonconverter.fotokraina.com/ but doesn't show the icon, so I'm not sure if it works or not.

SeaMonkey support would be appreciated. :)

Thanks.

**Comment by cooperq** [comment]
This is not something I have time for, but I would happily accept a pull request!

**Comment by cooperq** [comment]
this is a duplicate of EFForg/privacybadgerfirefox#126

**Comment by dr01** [comment]
This issue is not a duplicate anymore, since https://github.com/EFForg/privacybadgerfirefox became https://github.com/EFForg/privacybadgerfirefox-legacy and is not maintained anymore, as stated in the README.  Please, can it be reopened?

**Comment by ghostwords** [comment]
It might make sense to open a new issue, since so much changed since this issue was originally opened.

Does SeaMonkey support WebExtensions? If it does, what are the problems installing or using Privacy Badger with SeaMonkey?
