### ISSUE TITLE
Zendesk support centers are being erroneously blocked

### ISSUE THREAD

**Issue by wpg4665** [EFForg/privacybadgerchrome#485]
Companies leveraging the *Zendesk* "Help Center" (knownledge base), and using a custom URL, via CNAME, their CSS and JS assets are being blocked. Privacy badger will fully block, at least in the case, the URL `p6.zdassets.com`. Likely Zendesk is using `*.zdassets.com` to serve assets through HA.

This is unfortunate as these sites end up with NO CSS until the URL is unblocked, cookie blocking is still acceptable as these don't cause any layout isses.

I bring this up as a current customer of Zendesk, and on behalf of others. Test URLs:
* [help.masline.com](http://help.masline.com) (mine)
* [support.techsmith.com](https://support.techsmith.com) (another Zendesk customer)

**Comment by cooperq** [comment]
Sorry about the breaking! I will look into this, thanks for the bug report!

**Comment by SwartzCr** [comment]
for reference here is the privacy policy: https://www.zendesk.com/company/privacy/

**Comment by SwartzCr** [comment]
fixed in #510

**Comment by neeo** [comment]
I am also seeing this problem. But with the domain "assets.zendesk.com" and "(my site name).zendesk.com" being blocked. *.zendesk.com should be white listed!
