### ISSUE TITLE
Nudge the user to view the onboarding comic

### ISSUE THREAD

**Issue by cooperq** [EFForg/privacybadgerchrome#487]
There is still a danger that users will skip the onboarding slideshow (even though it looks super awesome!) and will just go right into it. 
We should put a window in the popup that users only see the first time they open it, the window should encourage the user to read the privacy badger onboarding comic and make sure they understand how it works. After that the user should not see the popup again.  This can probably be accomplished with a flag in local storage. Adding to chrome as well.

**Comment by SwartzCr** [comment]
same as: https://github.com/EFForg/privacybadgerfirefox/issues/434

**Comment by cooperq** [comment]
@taravancil do you have the interest and time to work on this?

**Comment by taravancil** [comment]
@cooperq working on it right now!

**Comment by cooperq** [comment]
:clap: :clap: :clap: :clap: Sorry to bother you then! Obviously way ahead of me :smile_cat:

**Comment by taravancil** [comment]
No worries. After I finish I'll work on https://github.com/EFForg/privacybadgerfirefox/issues/431 :+1:

**Comment by cooperq** [comment]
@taravancil how is work on this going? The firefox one looks great, and has been merged!

**Comment by taravancil** [comment]
Ah! I'm a dope. This fell off my radar. I'll do it right now. Thanks for the reminder.

**Comment by taravancil** [comment]
Done!
https://github.com/EFForg/privacybadgerchrome/pull/504 
Sorry about the delay :grimacing:

**Comment by cooperq** [comment]
No worries, you are awesome! Thanks for doing this! :tada:
