### ISSUE TITLE
Problems with blocking "consent.google.com"

### ISSUE THREAD

**Issue by KommX** [EFForg/privacybadgerchrome#503]
Google shows me (I guess it's my first visit after deleting all my cookies) a box "A privacy reminder...". When I hit "review" the content of the new layer doesn't load because "consent.google.com" gets blocked, see screenshot.

![google](https://cloud.githubusercontent.com/assets/7859245/8953308/a59e24b6-35dd-11e5-831e-3ab2f653cca8.png)

**Comment by SwartzCr** [comment]
I can't seem to reproduce this even in a private browsing window, can you give me better instructions to find this popup?

**Comment by KommX** [comment]
Sorry, right now I can't even reproduce this myself. :(

**Comment by KommX** [comment]
Now I saw this box again, but I still have problems to reproduce it.
But I'm still sure that blocking "consent.google.com" totally is a problem here.
