### ISSUE TITLE
weird subdomain handling

### ISSUE THREAD

**Issue by cooperq** [EFForg/privacybadgerchrome#506]
There is still an edge case where if b.scorecardresearch.com is user-allowed then sb.scorecardresearch.com is considered a subdomain and is also user allowed, but I will open that as a separate issue. 

basically .*{substring} is considered a subdomain of {substring}

**Comment by taravancil** [comment]
Yup, I've been able to reproduce this.

I also noticed that if you're on a page with both {substring}.host.com and  *{substring}.host.com, when you toggle {substring}.host.com to blocked, *{substring}.host.com goes away. It comes back if you toggle {substring} back to cookieblock or noaction.

**Comment by Kinnera323** [comment]
@taravancil and @cooperq 

@taravancil  If we consider, static.ak.facebook.com ( {substring}.host.com ) and s-static.ak.facebook.com (*{substring}.host.com) , when I toggle the static-ak.facebook.com to blocked, s-static.ak.facebook.com is still is the  previous state only. This is what I have observed in http://www.memes.com/  .Please provide me the website in which you are still facing this issue.

I have a slight confusion regarding the same considering domain and sub-domain.
Consider http://sourceforge.net/projects/recordmydesktop/files/recordmydesktop/ where two of its trackers are ml314.com and in.ml314.com. If we toggle ml314.com to blocked, it doesn't show the subdomain in.ml314.com as a tracker. I find no discrepancies in this issue. But I am unsure whether you considered this same issue in this example as a bug? 
The screenshots are here 
Before blocking ml314.com 
![fin1](https://cloud.githubusercontent.com/assets/9310107/10855201/45ed15ae-7f66-11e5-9a25-7f2d2bed85f6.png)

After blocking ml314.com
![subdomain2](https://cloud.githubusercontent.com/assets/9310107/10855202/45ef32a8-7f66-11e5-9e20-aa4bb2ccf6e0.png)

 

@cooperq if all these seem to be working well, you can close this issue.

**Comment by cooperq** [comment]
@Kinnera323 I suspect that what you are seeing in your sourceforge example is that ml314 loads content from in.ml314.com as a part of its process. When ml314.com is blocked in.ml314.com never gets a chance to load. This, as you suspected, is the correct behavior. 

To reproduce the issue that @taravancil and I are talking about you can take the following steps:
1. visit slashdot.org
2. open privacy badger, notice the state of b.scorecardresearch.com (blocked in my case)
3. move the slider for b.scorecardresearch.com to yellow or green
4. on reload notice that the slider for sb.scorecardresearch.com is also user yellow or user green now, even though you didn't set it that way, this is because privacy badger is incorrectly assuming that sb.scorecardresearch.com is a subdomain of b.scorecardresearch.com

**Comment by Kinnera323** [comment]
@cooperq In the website slashdot.org, there is only one tracker out of two trackers you mentioned ie., b.scorecardresearch.com and there is no sb.scorecardresearch.com in the trackers list. I am unsure of why this weird behavior with me. Here is the link to the screencast: https://drive.google.com/file/d/0B0UB8tkr05UxVXRzeFBUWm9RYlE/view?usp=sharing

**Comment by cooperq** [comment]
Ah, this appears to be because I am using https everywhere which forces the https version of scorecard research to load which loads that domain. If you install https everywhere you should be able to reproduce this.

**Comment by nextLane** [comment]
@cooperq I tried replicating the bug this side. b.scorecardresearch.com is appearing green initially. When I slide it to yellow and reload PrivacyBadger, sb.scorecardresearch.com still remains green as shown in the pic.
Same happens when I change it back to green. However when I change slider for b.scorecardresearch.com  to red, sb.scorecardresearch.com disappears from the list
![bug1](https://cloud.githubusercontent.com/assets/8895985/11098965/77f86fb4-88ce-11e5-85ba-7f42fed5b747.PNG)
What might go wrong here? 
This is happening in the second trial. I was able to replicate the bug once in start when b.scorecardresearch.com used to be Red, but now it has changed to green.
Also, I was going through getBaseDomain function, it seems correct. I am looking in Background.js file for the correction of this bug. Are there other places I should be looking for too?

**Comment by cooperq** [comment]
undo sb.scorecardresearch so that privacy badger has control of it and then move b.scorecardresearch.com to yellow, that should do the trick.
sb.scorecardresearch.com goes away when b.scorecardresearch is blocked because b loads sb.

**Comment by cooperq** [comment]
Okay, This should be completely fixed in the latest version of privacy badger. As of today I have only deployed it to 10% of users (it has some huge changes!) but if you want to try it out early you can take the following steps. 
1. Download the crx file [from the chrome web store] (https://clients2.googleusercontent.com/crx/blobs/QgAAAC6zw0qH2DJtnXe8Z7rUJP1rX98iOE5SwxVXgdVTMTKqobiCFyOuS_jNFoVMdRhW-bEA7QhvVJw2hrKrZS8b8ThMYsv0t-wxxLr4D-Sm2ZC1AMZSmuW2zjq5MsW529CVI2Rtq2QO7xWEQg/pkehgijcmpdhfbdbbnkijodmdjhbjlgp_main.crx)
2. Open a new tab to [chrome://extensions](chrome://extensions)
3. Drag the downloaded file and drop it onto the extensions window. 
You should now have Privacy Badger version 2016.5.15
If this doesn't fix the problem please let me know. If you find any new bugs please file a separate issue.
