### ISSUE TITLE
Whitelist disquscdn and vevo AND MORE

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadgerchrome#512]
So I just discovered that I've been stuck on the April 1, 2015 version of Privacy Badger. It wouldn't let me update to the new July 24, 2015 version. It showed as 'added to chrome' on the chrome web store. Clicking  'update extensions now' wouldn't do anything either. I had to remove the old version and manually download the new version.

I have another computer with the same Chrome profile and it's stuck on the old version too. Is this a known issue?

**Comment by cooperq** [comment]
Sorry for the confusion!
We have only released the new version to 5% of our users (at random) for
a chance to review any bugs before 1.0
All users will be auto updated to version 1.0 this week.

Closes #512

**Comment by terrorist96** [comment]
Oh ok, thanks for the info. I thought maybe I had missed a bunch of versions since April and been stuck on that version. I'll keep the old version on my other computer to see when I do indeed get the new version.

Thanks!

**Comment by terrorist96** [comment]
Also, the main reason I came here was because adm.fwmrm.net would block the video on:
https://www.vevo.com/watch/USQY51573982

Though I can't reproduce the issue on the new version or my other computer with the old version, I can reproduce it on Firefox with the old version. The default is set to red; it should be yellow. (Though it shows as green on the new version and the old version on my other computer - perhaps the algorithm hasn't figured it out yet?)

**Comment by terrorist96** [comment]
a.disquscdn.com breaks the comments. It should be yellow, not red by default.

Sent as an error report too, not sure if you actually see them though.

**Comment by terrorist96** [comment]
Chrome just gave me this warning regarding Privacy Badger:
Warning:
This extension is slowing down Google Chrome. You should disable it to restore Google Chrome's performance.

Damn, I think I shoulda stayed with the old version. :laughing:

**Comment by terrorist96** [comment]
![capture](https://cloud.githubusercontent.com/assets/12802056/9103962/ed1a14da-3bd2-11e5-95f0-510251e037d2.PNG)

**Comment by terrorist96** [comment]
> Also, the main reason I came here was because adm.fwmrm.net would block the video on:
https://www.vevo.com/watch/USQY51573982

This is now blocking the video again, and I have to manually move it to yellow (from red).

**Comment by terrorist96** [comment]
@cooperq

**Comment by cooperq** [comment]
Thanks for all the bug reports @terrorist96. I will look into whitelisting disqus and vevo. As for the chrome slowing down warning, it's a weird edge case, we are not actually slowing down chrome. See #473 for more info.

**Comment by terrorist96** [comment]
Thanks for the reply!

**Comment by terrorist96** [comment]
`uploads.disquscdn.com` needs to be defaulted to yellow too.

**Comment by terrorist96** [comment]
Video doesn't work. Need to make yellow `92275.cdx.c.ooyala.com`, `cf.c.ooyala.com`, `opf.ooyala.com`, and `player.ooyala.com`
http://fox40.com/2015/08/12/concealed-weapons-permits-on-the-rise-in-sacramento-county/

**Comment by terrorist96** [comment]
`api.viafoura.com` need to be yellow, not red.
Breaks comments:
http://www.timesunion.com/local/article/Judge-to-Cuomo-Administration-Hand-over-SAFE-Act-6443744.php

**Comment by cooperq** [comment]
Please open seperate issues for different sites. It's hard to keep track of all of them if they are all right here.

**Comment by terrorist96** [comment]
If you say so.
