### ISSUE TITLE
wow what is broken with https://blog.plex.tv/

### ISSUE THREAD

**Issue by SwartzCr** [EFForg/privacybadgerchrome#514]
A user reported that PB destroys https://blog.plex.tv/ and they're right
nothing is being blocked by PB (in the slider menu) but the page loads for a brief moment and then disappears!
Once PB is disabled it works again. I wonder if this has to do with their code erroring out when a cookie gets blocked?
requires some looking into

**Comment by SwartzCr** [comment]
I think it has to do with the social widget replacement, disabling social widget replacement causes the site to work again
@gunesacar would you be willing to take a look at this? this could be a big issue for launch

**Comment by taravancil** [comment]
I think it's because all of the site's markup is inside a `<fb:like>` element.

**Comment by SwartzCr** [comment]
oh, I had only thought to search for 'facebook' not fb
they have it as a self closing tag, but it fails to get rendered as self closing
I'm gong to leave a response on their forums and see if they'll fix this, thanks @taravancil for figuring this out!

**Comment by SwartzCr** [comment]
follow the progress here! https://forums.plex.tv/discussion/175716/plex-blog-gets-destroyed-by-eff-extension-privacy-badger-due-to-poor-html?new=1

**Comment by taravancil** [comment]
:+1: Hopefully they fix the issue soon!

**Comment by cooperq** [comment]
huh, that markup is... interesting...
