### ISSUE TITLE
greylist akamai.steamstatic.com

### ISSUE THREAD

**Issue by SwartzCr** [EFForg/privacybadgerchrome#515]
A user reports that http://store.steampowered.com/ breaks when store.akamai.steamstatic.com gets blocked by PB, possibly it should be added to the greylist
(I have confirmed that this does break the site)

**Comment by cooperq** [comment]
I wonder why steamstatic is getting blocked in the first place? It doesn't seem super likely that it would come up in multiple first party domains. Do you have a list of them?
