### ISSUE TITLE
First Run Comic Pointer to stay until user has browsed the comic

### ISSUE THREAD

**Issue by SwartzCr** [EFForg/privacybadgerchrome#516]
@taravancil made an awesome reminder to look at the first run page, but I'd really like it if we could make sure that people look at the comic. I wonder if it would be possible to keep showing this note until the user has actually clicked on the comic
(pr #504)

**Comment by taravancil** [comment]
I submitted a PR that keeps the reminder around until the user has at least scrolled to to the comic. It might make users mad if we expect them to click through the whole comic to get rid of the note. Let me know if scrolling to the comic is good enough, or if we should check that they at least click once!

**Comment by SwartzCr** [comment]
merged in #517!
