### ISSUE TITLE
Unable to play video on netflix

### ISSUE THREAD

**Issue by buren** [EFForg/privacybadgerchrome#518]
With Privacy Badger running, I was unable to play video on netflix. The reason being that `assets.nflxext.com` was completely blocked, when blocking just the cookies it works fine.

**Comment by sam5125** [comment]
shall I add this tracker to yellow list.

**Comment by buren** [comment]
I'm not sure if its needed anymore. Currently its listed as yellow for me.

**Comment by cooperq** [comment]
yea it looks like this has been added, thanks @sam5125 and @buren !

**Comment by buren** [comment]
:crown: @cooperq
