### ISSUE TITLE
Privacy badger 2015.8.5.1 does not display sliders

### ISSUE THREAD

**Issue by zeridon** [EFForg/privacybadgerchrome#524]
Hello Team,

After todays update PB no longer displays the sliders for detected trackers/etc when clicking on the icon (attched is a sample).

As you can see it says 4 trackers were blocked but clicking on the icon shows nothing.
![privacy-badger-no-sliders](https://cloud.githubusercontent.com/assets/5081863/9114665/b3ca16a8-3c63-11e5-8441-0fb05530060a.png)

**Comment by SwartzCr** [comment]
oh no! can you open up the browser console (ctrl+shift+j) and see if any errors are appearing in it?

**Comment by zeridon** [comment]
Yep there indeed is an error
````
Initializing popup.js
from addEventListener
Refreshing popup for tab id 79
Error in response to tabs.getSelected: TypeError: undefined is not a function
    at HTMLDocument.<anonymous> (chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/src/popup.js:712:15)
````

If it is of any concern the active tab was an youtube page (https://www.youtube.com/user/thatnikonguy/videos)

Issue exists also in incognito mode with only PB allowed to load. Loaded extensions: PB, Adblock and HTTPS Everywhere

**Comment by zeridon** [comment]
Additional notes:
* If there are no blocked trackers the popup shows fine
* As soon as there is at least one blocked tracker the popup gets broken and the sliders vanish.

**Comment by cooperq** [comment]
hmm, here is the contents of the anonymous function at line 712:
```
 console.log("from addEventListener");                                       
 refreshPopup(tab.id);  
```

it seems unlikely that `refreshPopup` is what's triggering this. do you maybe have console logging turned off?

**Comment by cooperq** [comment]
@zeridon are you still having this problem, I am unable to reproduce. Has anyone else had this problem?

**Comment by zeridon** [comment]
On пт, 2015-11-06 at 16:37 -0800, Cooper Quintin wrote:
> @zeridon are you still having this problem, I am unable to reproduce.
> Has anyone else had this problem?
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> 

Let me get back to you on tuesday (it has been some hectic months in
more than six different ways)
-- 
Regards
Vladimir Vitkov
