### ISSUE TITLE
Whitelisting not working v.2015.8.5.1

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerchrome#525]
Never had a problem with the previous version. streamin.to (embedded video) was blocked, so I whitelisted it via the slider multiple times and it remained blocked. I wound up getting the Chrome warning that Privacy Badger was slowing Chrome down, and it obviously was because I kept seeing "waiting for  Privacy Badger" in the corner. I went into the options and added it manually and that didn't work either. I'll have to disable it for now which is a shame because I really like it. I'll check back to see if it's resolved.

**Comment by SwartzCr** [comment]
I can't seem to reproduce this. Can you try removing privacy badger from your browser, re-installing it, and then see if this persists? We changed some things, and it'd be interesting to know if the updated versions of PB have an issue with this (as opposed to fresh installs)

**Comment by SwartzCr** [comment]
closing in favor of #526

**Comment by cypherpunk** [comment]
Chrome web store hasn't been updated. It's understandable if you want to test it first, but unpacked extensions are a pain in the ass in Chrome. I don't see a .crx anywhere

**Comment by cooperq** [comment]
It's in there. If it isn't updated yet, probably caching is to blame.

**Comment by cooperq** [comment]
I just looked and it appears that the new version of privacy badger is
under review in CWS. Nothing I can do about it, sorry. :(

- Cooper
