### ISSUE TITLE
settings being ignored

### ISSUE THREAD

**Issue by bitNomad** [EFForg/privacybadgerchrome#526]
Chrome Version 44.0.2403.125 (64-bit); OS X 10.9.5

I'm using a gmail add-on, streak CRM, that sets 3rd party cookies. I've attempted to set this to green in both settings and on the page itself, but they do not take. It seems like this is failing during a secondary load, so the first round of cookies goes through as planned, then gmail loads add ons and it fails. 

settings: 
![settings](https://cloud.githubusercontent.com/assets/45480/9117677/043fbd58-3c29-11e5-9741-25968a1c255c.png)

post page load: 
![post load](https://cloud.githubusercontent.com/assets/45480/9117689/1364b432-3c29-11e5-8f18-8641b064bfe2.png)

**Comment by SwartzCr** [comment]
I can't seem to reproduce this. Can you try removing privacy badger from your browser, re-installing it, and then see if this persists? We changed some things, and it'd be interesting to know if the updated versions of PB have an issue with this (as opposed to fresh installs)
(same as #525)

**Comment by SwartzCr** [comment]
(p.s. you have to reload the site with the tracker on it to see if the change propogates, though maybe you have?)

**Comment by SwartzCr** [comment]
for a brief moment I was able to reproduce this, and now I can't. It's not impossible that it only happens to certain domains. You could either include a screenshot with all the domains on a given site, or use the new error reporting button (at the bottom of the popup) and put which domains don't seem to be following your override actions in the message field (and then let me know here so I can try to find it in the database)

**Comment by cypherpunk** [comment]
Here's an example url: http://onlinehdmovies.org/four-brothers-2005-watch-online
Once Privacy Badger has determined streamin.to should be blocked, it won't allow it to be whitelisted.

**Comment by Jeroen52** [comment]
I have the same issue, whitelisting a domain, refreshing the page and it is blocked again.

**Comment by cypherpunk** [comment]
Also experiencing this bug. On derpiboo.ru, PB blocks derpicdn.net, and refuses to unblock it.

**Comment by cypherpunk** [comment]
I tried reinstalling and had no luck. It happens everywhere. Embedded videos get blocked with no way to unblock them. It's a shame, the previous version worked well.

**Comment by Jeroen52** [comment]
I also have it only in the latest version.

**Comment by carlo** [comment]
I'm running [a dotjs server](https://github.com/defunkt/dotjs) on `localhost:3131`. The related dotjs Chrome extension is fetching a JS script from there for each page I am visiting.

On any given page, PB will block the call to `localhost`.  I can seemingly whitelist the `localhost` domain using the settings overlay but when I reload the page (or visit any other page) `localhost` is blocked again.  The curious thing is that when I visit the PB Options screen, "User Filter Settings" tab, `localhost` is whitelisted there.

**Comment by cooperq** [comment]
@Jeroen52 I'm curious how you are whitelisting the domain? Are you using the sliders on the popup and trying to move it to green? Do you have local storage turned off?

**Comment by Jeroen52** [comment]
@cooperq I'm using the slider and I'm sliding it to green, I haven't turned off the local storage.

Whenever I slide it to green and afterwards the page is getting refreshed it is back at blocked.

**Comment by cooperq** [comment]
@Jeroen52 thanks! have you changed any other privacy or security related settings in your browser?

**Comment by cooperq** [comment]
Also, can you open the privacy badger debugging console by opening the privacy badger popup and then right clicking and clicking `inspect element`. Then click on the console tab and tell me if there are any errors, try moving a couple of sliders around and see if there are any errors after that?

**Comment by cooperq** [comment]
@bitNomad could you do the same things? And also tell me if you ahve changed any of the privacy or security settigns in chrome from their defaults?

Also could you both tell me if you had a previous version of the extension installed or not?

**Comment by Jeroen52** [comment]
I don't believe I have changed anything related to privacy or security in Chrome.

When loading a page.
GET [page getting blocked] net::ERR_BLOCKED_BY_CLIENT
Sliding it to green doesn't give an error.
Reloaded the page, still blocked.

**Comment by cooperq** [comment]
This should be fixed by the newest version 2015.8.14, please update your addons and try again.

**Comment by cypherpunk** [comment]
Chrome web store hasn't been updated. It's understandable if you want to test it first, but unpacked extensions are a pain in the ass in Chrome. I don't see a .crx anywhere

**Comment by cooperq** [comment]
Still waiting for the chrome team to review our extension....

**Comment by cypherpunk** [comment]
It seems to work as it should again. Well done.

**Comment by Jeroen52** [comment]
Works for me.
