### ISSUE TITLE
Extension Performance Warning

### ISSUE THREAD

**Issue by rbvea** [EFForg/privacybadgerchrome#527]
Running version  2015.8.5.1 I get this warning:

```
This extension is slowing down Google Chrome. You should disable it to restore Google Chrome's performance.
```

![screenshot 2015-08-06 10 07 37](https://cloud.githubusercontent.com/assets/949055/9122207/13cf775a-3c23-11e5-8a38-1e2753060738.png)

**Comment by SwartzCr** [comment]
It turns out this has to do with us updating chrome settings too much, and oddly has nothing to do with actual performance. See #473. We plan to fix this in the next major release of Privacy Badger.

**Comment by SwartzCr** [comment]
going to close in favor of #473

**Comment by rbvea** [comment]
Thanks for looking into it :+1:
