### ISSUE TITLE
whitelist s-msft.com

### ISSUE THREAD

**Issue by SwartzCr** [EFForg/privacybadgerchrome#528]
blocking it breaks style on https://gallery.technet.microsoft.com/ScriptCenter/site/search/?f%5B0%5D.Type=RootCategory&f%5B0%5D.Value=activedirectory&f%5B0%5D.Text=Active%20Directory

similarly blocking download-codeplex.sec.s-msft.com breaks https://pscx.codeplex.com/

**Comment by eduardog3000** [comment]
Also, `i-msdn.sec.s-msft.com`, which, when blocked, messes up https://msdn.microsoft.com.

**Comment by cooperq** [comment]
I think we just need to add s-msft.com to the cookieblock list. Clearly there are lots of domains for which it is a CDN.

**Comment by SwartzCr** [comment]
#583 for @cooperq to review
