### ISSUE TITLE
Imagus no longer shows gfycat then breaks imgur + others

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerchrome#532]
Problem is after the latest update last week? It broke Imagus.

I used to be able to hover the cursor over an image/link and Imagus would pop that image up so I could see without clicking as well as make the image larger. However, when Privacy Badger updated? I could hover on Imgur based images all day (and some others) and it would be fine. But gfycat images would just red circle spin all day and not pop up so I had to click them. And after the spinny wheel of death (not to be confused with the spinning beachball of death) Imgur and other images would pop up, but they would be just a white box the size of the image, but no image. 

I killed all extensions in Chrome and added Imagus and everything worked fine. I then checked them one by one until it would break, and Privacy Badger broke the image viewer. So I unchecked all but the Imagus and Provacy Badger and still it was broken.

Tried this with a 27" iMac running 10.10.4 and a 15" Retina MacBook Pro running 10.9.5 

Pic of hover over gfycat link the spinny circle will spin forever

<img width="777" alt="6fbebyo" src="https://cloud.githubusercontent.com/assets/97223/9140616/6d2dbb94-3ce7-11e5-9fc6-2d6fd2950552.png">

After attempting to hover over the gfycat link above, then all images get white boxed.
<img width="754" alt="after" src="https://cloud.githubusercontent.com/assets/97223/9140619/6f62993e-3ce7-11e5-8472-354e0b142da4.png">

**Comment by therealw00zy** [comment]
If you unblock giant.gyfcat.com in privacy badger it starts working again.
![image](https://cloud.githubusercontent.com/assets/17786541/13708272/a28ac36a-e77b-11e5-90cf-87d26fcdb3c7.png)

**Comment by cooperq** [comment]
Tell me, if you move giant.gfycat.com to yellow, does that also fix the issue?

**Comment by therealw00zy** [comment]
yes, Yellow appears to work fine.
