### ISSUE TITLE
badger blocks login via Clef

### ISSUE THREAD

**Issue by sterndata** [EFForg/privacybadgerchrome#536]
Clef is a two factor authentication system for WordPress and other platforms.  Privacy Badger blocks the site.  I have whitelisted both getclef.com and getclef.io without improving the situation.

More about Clef:  https://getclef.com/

**Comment by SwartzCr** [comment]
oh yeah, we should probably whitelist this

**Comment by cooperq** [comment]
@sterndata are you saying that whitelisting getglef.com and getclef.io didn't help? Can you let me know what other domains are blocked?

**Comment by sterndata** [comment]
@cooperq  Exactly.  I have whitelisted getclef.com, getclef.io, clef.com, and clef.io. When I try to access wp-admin on a site, clef.io shows in red.  If I slide it to green, I still am blocked. If I re-open the settings, it's back to red.

**Comment by cooperq** [comment]
Ah okay, so this is actually the same issue as in #526 et. al.

**Comment by cooperq** [comment]
This should be fixed by the newest version 2015.8.14, please update your addons and try again.
