### ISSUE TITLE
Please allow non-ad(?) images for http://www.der-postillon.com/

### ISSUE THREAD

**Issue by noyannus** [EFForg/privacybadgerchrome#539]
Please allow externally hosted images on http://www.der-postillon.com/
such as
http://1.bp.blogspot.com/-mLq6icxGT6s/UjDqcGEVtTI/AAAAAAAAWh8/btuaRLxqbr8/s308/Mario3.jpg

And: THANKS FOR SUCH A GREAT BLOCKER!

**Comment by SwartzCr** [comment]
It seems like blogspot was being blocked for you. Blogspot is on the cookie exceptions list, so this shouldn't happen again.
