### ISSUE TITLE
Unblocking domain doesn't work - keeps reverting to red (BLOCKED)

### ISSUE THREAD

**Issue by SteveRidout** [EFForg/privacybadgerchrome#540]
I create the Chrome extension [Readlang Web Reader](https://chrome.google.com/webstore/detail/readlang-web-reader/odpdkefpnfejbfnmdilmfhephfffmfoh) which injects some javascript into a page when the user clicks a toolbar button.

I've had a report from a user who keeps sliding readlang.com to green in Privacy Badger to allow it, but the next time he clicks my toolbar icon to load Readlang on a different page it reverts back to red (BLOCKED)

He's also tried adding readlang.com to the whitelisted domains in settings but the problem remains.

I can confirm that the problem is reproducible.

Why is this happening? Seems like a bug.

**Comment by sterndata** [comment]
I can replicate that problem, too.

**Comment by eternal-sorrow** [comment]
I confirm this problem on many sites. Since recent update Privacy Badger completely ignores my custom settings and blocks domains I don't want to be blocked, but unblocks what I want to block.

**Comment by SwartzCr** [comment]
what OS are you running? We've heard some reports for this on Windows, but I can't seem to reproduce it on linux

**Comment by sterndata** [comment]
I'm using Fedora 22

**Comment by SteveRidout** [comment]
I can reproduce with OSX Yosemite

**Comment by eternal-sorrow** [comment]
I use privacy badger on two different PCs. One with windows 10, another with Gentoo Linux and have this issue on both.

**Comment by cooperq** [comment]
@sterndata @eternal-sorrow @SteveRidout do you guys have local storage turned off, or any other non standard settings in your browser? What other extensions are you running.

**Comment by eternal-sorrow** [comment]
I don't have local storage turned off and all others setting from chrome://settings/ are pretty standard, but I turned on some features in chrome://flags and I have some other extensions. Here is full list:
```

APNG 2.1.5
Don't track me Google 3.6
HTTPS Everywhere 2015.7.17
Instant Translate 2.8.3
IPA furigana 1.12
PDF Viewer 1.1.132
Privacy Badger 2015.8.5.1
Random (Hide) User-Agent 1.5.4
Reedy 2.2.13
Referer Control 0.59
Requestly 3.3.8
Search by Image (by Google) 1.5.1
The Great Suspender 6.19
uBlock Origin 1.0.0.1
WOT: Web of Trust, Website Reputation Ratings 2.6.3
```

**Comment by sterndata** [comment]
Nothing fancy

Bit.ly
Currently
FlashBlock
Google Docs
Googel Play Music
Google Slides
Google Sheets
Hangouts

**Comment by cooperq** [comment]
One final question. Did you have a previous version of privacy badger installed, or did you install it for the first time with 1.0?

**Comment by sterndata** [comment]
I started with 1.0

**Comment by eternal-sorrow** [comment]
I had previous version installed.

**Comment by cooperq** [comment]
This should be fixed by the newest version 2015.8.14, please update your addons and try again.

**Comment by SteveRidout** [comment]
Thanks @cooperq! Works by loading chrome-2015.8.14 tag as unpacked extension.

The new version isn't available on the Chrome Web Store yet, hopefully it will be soon so I can advise my users.

**Comment by cooperq** [comment]
Still waiting for chrome team to review our extension...

**Comment by sterndata** [comment]
I just installed 2015-8-14 from Google.

**Comment by eternal-sorrow** [comment]
Just got fresh version of extension from chrome webstore. Seems like problem is gone. Thanks!
