### ISSUE TITLE
Rapportive

### ISSUE THREAD

**Issue by lydialaurenson** [EFForg/privacybadgerchrome#541]
Hi there!  Thanks for all your hard work on Privacy Badger and everything else.  <3  

It looks like Privacy Badger doesn't play well with the Chrome extension Rapportive.  When PB is turned on, I receive a "Rapportive is offline" message from Rapportive.  I use this extension pretty much constantly, so I had to turn off Privacy Badger :(  Let me know if I can help in any way to fix this.

**Comment by hansika** [comment]
Hi,
@lydialaurenson After some testing I could realize that Rapportive still works fine when you yellowlist rapportive.com, platform.linkedin.com domains and whitelist linkedin.com domain. You can still have the facility of Rapportive on Gmail without completely disabling Privacy Badger.
