### ISSUE TITLE
Are Vines from vine.co blacklisted?

### ISSUE THREAD

**Issue by dieseltravis** [EFForg/privacybadgerchrome#543]
![image](https://cloud.githubusercontent.com/assets/17863/9176118/6dbddfe0-3f57-11e5-9da7-3d793c31f0a0.png)

The slider for `platform.vine.co` retains whatever setting I leave it at, while `vine.co` always reverts to blocked. I experienced this on http://mlkshk.com/p/15D2U

Chrome 44.0.2403.130 m (64-bit)
Privacy Badger 2015.8.5.1
Windows 10

**Comment by dieseltravis** [comment]
This might actually be a duplicate of https://github.com/EFForg/privacybadgerchrome/issues/540

**Comment by dieseltravis** [comment]
And that one might actually be a dupe of https://github.com/EFForg/privacybadgerchrome/issues/526

**Comment by cooperq** [comment]
I think you are correct.

**Comment by cooperq** [comment]
This should be fixed by the latest update.
