### ISSUE TITLE
Google Chrome giving warning Please fix this

### ISSUE THREAD

**Issue by Aabhi021290** [EFForg/privacybadgerchrome#548]
![untitled](https://cloud.githubusercontent.com/assets/11795895/9200834/6a49ccfa-4067-11e5-9492-7d2e0faa5349.png)

**Comment by kristian-hermansen** [comment]
I also am seeing this as of today.

**Comment by kristian-hermansen** [comment]
![screenshot from 2015-08-11 10 35 43](https://cloud.githubusercontent.com/assets/355620/9205125/2f51203c-4015-11e5-9d83-a9c4c8760890.png)
![screenshot from 2015-08-11 10 36 15](https://cloud.githubusercontent.com/assets/355620/9205130/32be9bf0-4015-11e5-8791-9bf4e7de72bd.png)

**Comment by cooperq** [comment]
This is a known issue, see #473
