### ISSUE TITLE
Phantom domains in tracking list

### ISSUE THREAD

**Issue by 9Yg1rxeSeha90ZU1** [EFForg/privacybadgerchrome#550]
Invisible / "phantom" domains are showing up on sites like Google Drive / Docs. See attachment.

Also, possibly related, I have noticed odd behaviour when moving domains from Green to Yellow or Red that they do not stay where I placed them after I have created a long list of custom blocks. They seem to be ignored or go back to Green.

![screenshot from 2015-08-11 12 32 36](https://cloud.githubusercontent.com/assets/355620/9207887/2e431d84-4025-11e5-8ec7-ebd50288e3dc.png)

**Comment by cooperq** [comment]
I have been unable to reproduce this, can anyone else confirm this or give me steps to reproduce?

**Comment by kristian-hermansen** [comment]
Try adding more than 1000 custom settings for domains and you should start to notice very odd behavior, not just the phantom domains but also inability to change settings for domains.
