### ISSUE TITLE
PrivacyBadger Slowing Down Chromium

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerchrome#552]
Hello,

I am recently using PrivacyBadger to block tracking and advertisement (partially)
Today I got an extension error from Chromium. 
It says "This extension is slowing down Chromium. You should disable it to restore Chromium's perfromance"
Here is the screenshot : http://i.hizliresim.com/95LWqo.png

Can you please do something about it?

Thanks

**Comment by justechn** [comment]
I am getting the same message on multiple computers

**Comment by tgaff** [comment]
I've had the same issue and it's a very noticeable slowdown (even on a new i7 machine).  It adds in my estimate between 0.5-3 seconds per page load.

**Comment by cooperq** [comment]
Duplicate of #473. A fix will be released shortly.
