### ISSUE TITLE
blocking script.ioam.de breaks http://www.inside-handy.de/

### ISSUE THREAD

**Issue by KommX** [EFForg/privacybadgerchrome#554]
1. Go to http://www.inside-handy.de/handys/motorola-moto-g-3-gen/test
2. Try to click the right arrow button (to see the next picture)
3. It doesn't work as long as script.ioam.de is blocked by PB.

**Comment by SwartzCr** [comment]
if you could kindly point us to a privacy policy for ioam.de that would help greatly in making us feel confident that adding it to the cookie exception list would be a good idea

**Comment by KommX** [comment]
I have found this:
https://www.infonline.de/de/extra/datenschutzallgemein/

But it only seems to be available in German.

In general, I think, PB is right when blocking it since it seems to be some kind of tracking but unfortunately it breaks some sites. So perhaps just blocking their cookies is a better idea.

**Comment by cooperq** [comment]
according to the translated privacy policy:
```
When using an online service (website, smartphone application etc.), employing the next flights from Infoline technology to measure be triggered counts and stored by Infoline. The case transferred IP addresses are cut in the first processing step by 1 byte and further processed until after the reduction. Log files that contain abbreviated IP addresses will be deleted after 60 days. At no time individual users are identified.
```
this seems fine to me, also there appears to be some provisions for users expressing DNT, I think we can safely add this to the yellowlist.
