### ISSUE TITLE
Privacy Badger throws cryptic messages at the console without identifying itself as their source.

### ISSUE THREAD

**Issue by nekromoff** [EFForg/privacybadgerchrome#555]
https://stackoverflow.com/questions/31953321/firefox-40-what-does-the-found-hi-entropy-localstorage-message-mean

confirmed by browsing to http://localhost

**Comment by SwartzCr** [comment]
is this a firefox issue? I don't think chrome PB prints to the main browser console (while the firefox one definately does)
We should maybe add a setting to turn on logging and have it off by default, but in the mean time maybe you want to close this issue and move it to the firefox issue list? https://github.com/EFForg/privacybadgerfirefox/issues
