### ISSUE TITLE
Images not shown on website

### ISSUE THREAD

**Issue by orschiro** [EFForg/privacybadgerchrome#556]
Hi all, 

I have a problem with the following website with activated privacy badger:

http://www.lifehack.org/300603/websites-that-successful-entrepreneurs-should-always-visit

Images are not shown. Can anyone confirm this issue?

Thankfully,

Robert

**Comment by cooperq** [comment]
@orschiro can you tell me which domains privacy badger has blocked on lifehack.org?

**Comment by orschiro** [comment]
@cooperq 

I am not sure what has changed since I reported this, but now upon checking again, the images are shown. Apologies for the confusion. I will close this issue and re-open if I can reproduce the issue again.

Robert
