### ISSUE TITLE
Whitelisting doesn't work as desired

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerchrome#561]
I understand that whitelisting is for disabling PB on a certain website. But I want to stop it from blocking a certain tracker on ALL websites. There's no way to do it. It disables one add-on that I use that has a recognized tracker (which I don't mind).

**Comment by cooperq** [comment]
you can do that in the options page. If you click on the gear icon in the privacy badger popup, you can move the slider for a tracker to green and it will stop blocking that domain and any subdomain on all pages.
