### ISSUE TITLE
Plug-in compatibility issue

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerchrome#562]
Referer Control 0.59 

Warning:
This extension failed to modify the request header "Referer" of a network request because the modification conflicted with another extension (Privacy Badger).

**Comment by cooperq** [comment]
This is because we strip the referer header from requests to domains that are cookie blocked.

**Comment by semente** [comment]
@cooperq can't you add a option to disable it? Even if it is hidden/available only from about:config. Would it solve this conflict?I prefer use uMatrix extension to spoof HTTP referer because I can enable it for all websites.

**Comment by semente** [comment]
@cooperq is there any chance of my request above be ever implemented? I'm looking for a solution for this issue. Other option may be have a option to Privacy Badger do referer spoofing for all websites.

**Comment by cooperq** [comment]
@semente I might consider an option to always spoof the referer header. What does umatrix replace the referer header with? Or does it just strip it? Please open a new issue for this feature request.

**Comment by semente** [comment]
@cooperq awesome!

> If this setting is checked, uMatrix will spoof the HTTP referrer information if the domain name of the HTTP referrer is third-party to the domain name of net request.

I think it is the best setup. Spoofing all requests may cause some issues (at least I already had authentication issues with some websites). Other option is send the URL you are going to visit as the HTTP referrer, but I found uMatrix solution better.

**Comment by ghostwords** [comment]
Related to #1134.
