### ISSUE TITLE
"This extension is slowing down Google Chrome"

### ISSUE THREAD

**Issue by giacecco** [EFForg/privacybadgerchrome#563]
Hi All, I got the message you see below once in the first days using Privacy Badger on the latest Chrome for MacOS. I realised about the problem when the "hamburger icon" became orange as when new Chrome versions are available for installation. I clicked on it and I got notification of the issue, then I went into the extensions configuration and saw what is in the screenshot.

![screen shot 2015-08-16 at 18 58 19](https://cloud.githubusercontent.com/assets/303693/9324002/3387c52a-457e-11e5-949d-7594c5e9aa0f.png)

Unfortunately I did not think of writing down what websites I was visiting so to determine what could have caused that. It would be useful if Privacy Badger had that capability to save its host browser's "status" to help debugging.

I will write again next time I bump into the issue.

G.

**Comment by cooperq** [comment]
Please update to the latest version of privacy badger where we have fixed this problem. See #530
