### ISSUE TITLE
Cookie blog list not applying to subdomains

### ISSUE THREAD

**Issue by woky** [EFForg/privacybadgerchrome#564]
Currently YouTube video playing doesn't work with Privacy Badger. It seems that it's blocking googlevideo.com but I can't tell for sure because the domain list doesn't expand horizontally. The list doesn't expand in options page neither.

![](https://i.imgur.com/zsme8Aw.png)

(It also seems that "*.googlevideo.com" in new whitelist doesn't work but I'll leave it for separate issue once I'll see full domain in the list).

**Comment by cooperq** [comment]
The real issue here is that the cookie block list appears to not be working as expected in chrome either. googlevideo.com is already on the cookie block list, so any subdomains of it should be cookieblocked instead of full blocked, but that appears to not be the case. We need to correct this.

**Comment by woky** [comment]
Well, sure that's an issue, but the list not widening is an issue too. Please don't limit its maximum width.

**Comment by cooperq** [comment]
We have to limit it's maximum width, though there may be a better workaround

**Comment by woky** [comment]
Then don't limit its width to measly 100 or so pixels and make it expand whole screen. It's pointless to talk here about *real issue* when neither of us can certainly say which domain is actually blocked. Is it googlevideo.com or googlevideo.super-ads.com?

**Comment by cooperq** [comment]
this is fixed by #635
