### ISSUE TITLE
Breaks Amazon Customer Service

### ISSUE THREAD

**Issue by literallyanything** [EFForg/privacybadgerchrome#565]
Once I get onto the customer service page, none of the links work. Cannot click contact, cannot pick another order, nothing.

**Comment by SwartzCr** [comment]
would you mind posting a screenshot of Privacy Badger's settings when you're on the customer service page (and linking us to it as well) so we can see which blocked third party is causing the issue? That would help us a lot!

**Comment by literallyanything** [comment]
This is the page: http://www.amazon.ca/gp/help/customer/display.html/ref=gw_m_b_he?ie=UTF8&nodeId=915404

These are the blocks: http://i.imgur.com/72rRvWx.png

I think it's obvious which one needs to be changed to yellow level.

**Comment by SwartzCr** [comment]
The full URL is: amazoncustomerservice.d2.sc.omtrdc.net
I tested and I can confirm that although the site doesn't look broken the contact us button no longer works

**Comment by SwartzCr** [comment]
This seems to be an Omnicom domain that is a slightly creepy CDN, I wonder if this is only a problem on amazon.ca (isn't it ridiculous that that's actually a completely different site than amazon.com?)
If we add it to the cookie list I'd add only that specific domain and not a parent of it
