### ISSUE TITLE
Difference between Privacy Badger for Firefox and Chrome

### ISSUE THREAD

**Issue by Garve** [EFForg/privacybadgerchrome#566]
Hi!

I installed Privacy Badger for both browsers, but the extensions behaves differently. In Firefox more things are blocked, in Chrome many domains are listed under 'The domains below don't appear to be tracking you', which is not even present in Firefox.

So, does the Firefox version block too much, or the Chrome version not enough? I think it is probably the second version, because Google Analytics is blocked in Firefox, but not in Chrome.

**Comment by maranomynet** [comment]
Could it be that your Firefox has more browsing history (and built-up cookies, localStorage, etc.) which might help PB (Privacy Badger) deduce which sites are trackers?

Also, If you've used Firefox more since you installed PB it will have collected more diagnostics data.

**Comment by Garve** [comment]
Hi!

No, cookies are always deleted every few seconds (Self Destructing cookies addon). And no, Privacy badger even reset itself in my Firefox version for some reason, still it learns much faster than the Chrome version. And still no 'The domains below don't appear to be tracking you' in the Firefox version, on no site.

**Comment by cooperq** [comment]
Firefox and chrome will have different lists based on different browsing histories and settings, and different resources being loaded for different browsers. It is not a reasonable or plausible design goal to have them look the same all the time.

**Comment by SwartzCr** [comment]
I've also noticed that various sites set cookies differently based on user agent, which when I initially saw I was sure was a bug in privacy badger until I inspected some of the requests. Additionally if you have different adblockers running in addition to privacy badger then that can also cause this issue
