### ISSUE TITLE
Crashes Chrome when disabled/removed

### ISSUE THREAD

**Issue by DidUknowiPwn** [EFForg/privacybadgerchrome#568]
Wanted to disable the extension for a quick second to test something but it keeps crashing instantly when I try to.

It also crashes when you attempt to uninstall.

build Canary 46.0.2486.0

**Comment by DidUknowiPwn** [comment]
build 46.0.2488.0 fixed the issue.

**Comment by cooperq** [comment]
Chrome bug then.

**Comment by DidUknowiPwn** [comment]
More than likely, I only opened the issue as it was with this specific plugin only. So ¯\_(ツ)_/¯
