### ISSUE TITLE
Dual licensing

### ISSUE THREAD

**Issue by pde** [EFForg/privacybadgerchrome#570]
Several companies are interested in doing ports of Privacy Badger to other platforms. Although the ports would all be open source, it's possible some of these ports would be used in proprietary systems. We need to check with all contributors whether this is an acceptable change, and then update the licensing file.

**Comment by pde** [comment]
I am emailing most contributors to see if they're okay with this change.  But there are some I don't have email addresses for... @SomMeri @fauved @justin-

**Comment by cooperq** [comment]
I don't have emails for them either, hopefully they can give their approval here in this issue thread.

**Comment by SwartzCr** [comment]
Is it possible to list the specific licensing requests here?

**Comment by SomMeri** [comment]
I do not mind code being used in proprietary system. Do you have specific standard license in mind?

**Comment by cooperq** [comment]
I think one of the permissive open source licenses but I"m not exactly sure which one.

**Comment by pde** [comment]
@SomMeri it will either be Apache or BSD-style, possibly with a separate patent shield for the Privacy Badger community; we are still negotiating those details.

If you're okay with the change, can you send me an email (my username at eff.org) with the form below filled out and signed?  A PGP signature is perfect, a photo of a signed copy is perfect, an email saying that you "hereby sign this document" will work in a pinch.

```
PRIVACY BADGER CONTRIBUTOR PERMISSION TO RE-LICENSE                                                                                                                      
I, an individual, contributed code or other works of authorship (the                                                                                                     
Contribution) to the Privacy Badger software (the Work) through the                                                                                                      
Electronic Frontier Foundation, a non-profit organization incorporated                                                                                                   
in the Commonwealth of Massachusetts (EFF).                                                                                                                              
                                                                                                                                                                         
In consideration of the publication of the Contribution as part of the                                                                                                   
Work, and in order to advance EFF and Privacy Badger's mission, I hereby
grant EFF a non-exclusive, worldwide, perpetual, royalty-free license to
copy, distribute, modify, perform, adapt, or otherwise use the
Contribution under the terms of any license or licenses that comply with
the Debian Free Software Guidelines as promulgated by the Debian Project,
such license or licenses to be selected by EFF at its sole discretion,
and to authorize others to do the same under the terms of any such
license or licenses.

I represent that I have the legal ability to grant this license to the
Contribution, and have not entered into any assignment, contract, or
understanding in conflict with this license.

By my physical or electronic signature on this document, I agree to the
terms above.

Name _______________________________________________________


Address ____________________________________________________

        ____________________________________________________



Date ____________________________________
```

**Comment by pde** [comment]
Also nudging @pirsquared for contributions to the Firefox port.

**Comment by justin-** [comment]
I trust the EFF to make sensible licensing decisions. I'm fine with the proposed changes.

**Comment by SwartzCr** [comment]
i believe this has been resolved
