### ISSUE TITLE
gigya comments broken

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadgerchrome#575]
cdn.gigya.com
cdn1.gigya.com
cdns.gigya.com
comments.us1.gigya.com

These need to be defaulted to yellow, instead of red. Otherwise, they break comments on websites. Example:
http://bizbeatblog.dallasnews.com/2015/08/huge-data-center-will-replace-old-hotel-near-downtown-dallas.html/

**Comment by SwartzCr** [comment]
except that gigya seems like an awful tracker: https://www.gigya.com/ which is probably why they're setting those cookies in the first place (while acting as a CDN)
I'm going to close this issue, if you can convince me that they should be added to the cookie block list (i.e. they conform to the guidelines: https://github.com/EFForg/privacybadgerchrome/blob/master/yellowlist-criteria.txt) then feel free to re-open this
