### ISSUE TITLE
api.viafoura.com

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadgerchrome#576]
api.viafoura.com need to be yellow, not red.
Breaks comments:
http://www.timesunion.com/local/article/Judge-to-Cuomo-Administration-Hand-over-SAFE-Act-6443744.php

**Comment by SwartzCr** [comment]
I'm worried that viafoura is a tracker: http://viafoura.com/
if you can convince me that they conform to the guidelines for yellow list additions please re-open this ticket:
https://github.com/EFForg/privacybadgerchrome/blob/master/yellowlist-criteria.txt
