### ISSUE TITLE
ooyala.com

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadgerchrome#577]
Video doesn't work. Need to make yellow 92275.cdx.c.ooyala.com, cf.c.ooyala.com (this can be red and the video will work, but won't display the video thumbnail, so should be yellow), opf.ooyala.com, and player.ooyala.com
http://fox40.com/2015/08/12/concealed-weapons-permits-on-the-rise-in-sacramento-county/

**Comment by SwartzCr** [comment]
I'm similarly concerned that ooyala is a tracker. maybe @cooperq can weigh in on this?

**Comment by terrorist96** [comment]
I thought making it yellow blocks cookies, so it still can't really track you. Or am I wrong?

**Comment by cooperq** [comment]
They seem to do a number of things including serving video, analytics, and tracking. If blocking them is breaking video on some sites we may need to consider moving some domains to the yellow list, but I want to be very careful about what we put on the yellow list. We should only put the absolute minimum number of domains that are needed to display video. 

Making it yellow does block cookies, but there are still other ways that a tracker can track you, such as supercookies and fingerprinting.

**Comment by cooperq** [comment]
I think this can be treated as low priority.

**Comment by terrorist96** [comment]
> I think this can be treated as low priority.

Can you please explain your thought process for reaching that conclusion? If Privacy Badger breaks critical functionality on a site, I see that as high priority. Interested to hear your perspective.

**Comment by cooperq** [comment]
@pde do you want to weigh in on this?

**Comment by terrorist96** [comment]
Guess not.
In addition, ak.c.ooyala.com breaks the video here:
http://mashable.com/2012/09/13/six-degrees-kevin-bacon/

**Comment by terrorist96** [comment]
New version is out. Was this ever addressed?

**Comment by cooperq** [comment]
This has not been addressed. I think that the solution here is to add ooyala to the things that give you a popup so that the user can decide for themselves whether or not they want to watch the video enough to allow ooyala to track them.

**Comment by terrorist96** [comment]
Just adding another example:
http://wreg.com/2016/03/27/tennessee-legislature-focuses-on-guns/

need to yellowlist the following for video to work:
`player.ooyala.com`
`32724.cdx.c.ooyala.com`
`opf.ooyala.com`
need to yellowlist `cf.c.ooyala.com` for the video thumbnail to appear

**Comment by terrorist96** [comment]
http://fox17online.com/2016/04/04/public-forum-on-gun-control-sparks-debate-in-kalamazoo/

`92261.cdx.c.ooyala.com`
`opf.ooyala.com`
and
`player.ooyala.com`
need to be yellow in order for the video to work.

**Comment by terrorist96** [comment]
So it's been about 9 months since this was reported. Any update?

**Comment by terrorist96** [comment]
http://www.theverge.com/2016/5/10/11649332/nikola-motor-company-turbine-powered-electric-big-rig-truck-concept

**Comment by cooperq** [comment]
Okay fine, I have tested this for replacement and it doesn't look like that's going to work so I have added it to the cookie block list.

**Comment by terrorist96** [comment]
Just  to clarify, this will be in the next release? Your comment was made on the 24th of May, and the most recent version of PB is May 24th, so I'm not sure if this change was made before or after the release, since ooyala still defaults to red for me.
Thanks

**Comment by terrorist96** [comment]
To clarify: some ooyala domains are now yellow, but some are still red, so all the videos I posted above still fail to play. Looks like the required domains to be moved to yellow have changed since when I made the original posts.

**Comment by cooperq** [comment]
I added *.c.ooyala.com player.ooyala.com api.ooyala.com and l.ooyala.com
tell me what else we need to add. (or make a pr adding the nececsary domains.)

**Comment by terrorist96** [comment]
I'll attempt a PR. What's the difference between the `sample_cookieblocklist.txt` and `sample_cookieblocklist_legacy.txt`?

Will I need to make a PR for both or just the non-legacy one?

**Comment by terrorist96** [comment]
Only `opf.ooyala.com` needs to be added.

**Comment by terrorist96** [comment]
http://www.space.com/33185-earth-quasi-moon-asteroid-2016-ho3.html

**Comment by terrorist96** [comment]
http://www.telegraph.co.uk/news/2016/06/22/eu-referendum-poll-the-latest-tracker-and-odds/

@cooperq can you merge my PR for this? It's been 19 days.

**Comment by cooperq** [comment]
Merged!
