### ISSUE TITLE
adm.fwmrm.net

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadgerchrome#579]
adm.fwmrm.net needs to be yellow; blocks the video on:
https://www.vevo.com/watch/USQY51573982

**Comment by SwartzCr** [comment]
again I'm afraid this is a tracker, can you make an argument for this third party?

**Comment by terrorist96** [comment]
It breaks the video? Watching the video is the primary purpose of the site.

**Comment by terrorist96** [comment]
I can understand not wanting to unblock comments on sites because those are secondary functionalities. But a video on a site is primary function.

**Comment by cooperq** [comment]
This is in the same grey area as ooyala. It is definitely needed to watch video on vevo, but they are definitely a tracking company. My intuition is that we should cookie block the minimum number of domains needed for video to work, but I am curious what @pde thinks about this?

**Comment by terrorist96** [comment]
Who is this mysterious @pde that never seems to want to offer his thoughts?

**Comment by cooperq** [comment]
I think the same thing applies here. We should add fwmrm to the popup list to allow the user to make the decision.

**Comment by terrorist96** [comment]
Here's another example of `adm.fwmrm.net` blocking a video:
http://www.huffingtonpost.com/entry/donald-trump-middle-east-would-be-better-off-with-saddam-gaddafi_56116b78e4b0768127025efd

**Comment by terrorist96** [comment]
And another example of where `adm.fwmrm.net` breaks a video:
http://www.fyi.tv/shows/kocktails-with-khloe/season-1/episode-2

**Comment by cooperq** [comment]
Again, this is  an excellent candidate for #400

**Comment by terrorist96** [comment]
Another example: http://www.adultswim.com/videos/infomercials/icelandic-ultrablue-phase-one/

**Comment by cooperq** [comment]
okay so I looked into this more, it seems like it's breaking enough stuff that we need an urgent fix. It isn't a good candidate for the domain exception popup, script surrogates, or widget replacement. I looked at the tracking and it seems to just be cookie based so I think we are safe to add this to the cookieblock list. I have done so in 1fda4d93fbc4d0ce4b60f8be48fac22e1a7679f7

**Comment by terrorist96** [comment]
@cooperq I got the latest update (April 6) and `adm.fwmrm.net` still defaults to red on the above sites.

**Comment by terrorist96** [comment]
`29ccd.v.fwmrm.net` is blocking the video
http://www.fyi.tv/shows/kocktails-with-khloe/season-1/episode-13/episode-13-highlights
