### ISSUE TITLE
First run page pointer isn't obvious enough

### ISSUE THREAD

**Issue by SwartzCr** [EFForg/privacybadgerchrome#585]
I've done some hallway testing, and continue to get screenshots where people haven't gotten rid of the 'learn how privacy badger is protecting your browser' dialogue. I'm afraid that people don't realize that they can get rid of it, leading to permanently reduced screen pop-up size.

My two initial thoughts on what to do are to have the orange button in the pop-up animate (maybe bounce) to draw attention to people to click it, and then to have a similarly animated arrow pointing at the 'next panel' button on the first run page.

I'm going to tag @taravancil in case she has opinions on this since she made the original

**Comment by cooperq** [comment]
:+1:

**Comment by taravancil** [comment]
I like that idea. It's too big to stay in the popup! What about animating it and also hiding it after the popup has been open a set number of times? Even with an animation, I imagine some people will *never* click it.

I'll do this over the weekend!

**Comment by cooperq** [comment]
What about putting it on top of the rest of the window, and making it more apparent that you should click on it? Maybe this needs some A B testing.

**Comment by SwartzCr** [comment]
@taravancil do you think you still have time to take a crack at this? Otherwise I might try to assign it to a prospective intern

**Comment by Tahirih-Natang** [comment]
@SwartzCr I think I can take a look at this! But a good number of proposals have been made on how to enhance this feature. But what if we just add an image that carry the message "Click on me to Learn ........."

**Comment by SwartzCr** [comment]
@Tahirih-Natang The current status is there is a large orange box that says that, but people aren't clicking on it! We want to make it more obvious and harder to ignore

**Comment by Neha--Agarwal** [comment]
How about making a semi transparent layer over the popup for the first time when the extension is installed? Once the user clicks a button which says something like 'Got it', we can move the "learn text" in the way it is at present.

**Comment by Tahirih-Natang** [comment]
Here:
https://github.com/Tahirih-Natang/privacybadgerchrome/commit/35dbb10c80cf3233450c17b7382697c431fac185

**Comment by cooperq** [comment]
I think that maybe something like what @Neha--Agarwal suggests would be a good plan maybe with some modification, lets have a semi transparent layer over the popup that doesn't go away until the user clicks to see the slideshow (we don't have to show it at all if the user has already viewed the slideshow). I think that this could replace the orange box that's there now entirely.
