### ISSUE TITLE
feature request: allow wildcards in whitelisted domains

### ISSUE THREAD

**Issue by michaelperret** [EFForg/privacybadgerchrome#588]
Currently setting `*.gooddomain.com` in the whitelisted domains section of the settings still runs privacybadger on `foo.gooddomain.com`

It would be super useful to have the ability to allow/disallow entire subsets of domains.

**Comment by SwartzCr** [comment]
oh that's because the whitelisting doesn't understand *
You need to add gooddomain.com to the list and then it should work

**Comment by michaelperret** [comment]
@SwartzCr I've added `wake.io` but all the subdomains still have privacy badger running. (see screenshots) 

Am I doing something incorrect here?

<img width="1095" alt="screen shot 2015-09-14 at 5 56 03 pm" src="https://cloud.githubusercontent.com/assets/1673044/9865372/25a215ae-5b0a-11e5-8642-75e39388087c.png">
<img width="1100" alt="screen shot 2015-09-14 at 5 56 52 pm" src="https://cloud.githubusercontent.com/assets/1673044/9865374/25a2df02-5b0a-11e5-8423-3eb16fd40f3f.png">
<img width="1234" alt="screen shot 2015-09-14 at 5 57 12 pm" src="https://cloud.githubusercontent.com/assets/1673044/9865373/25a2951a-5b0a-11e5-956d-31e136d488cc.png">

**Comment by cooperq** [comment]
Sorry, you are totally correct, this feature does not currently work! We will add this to the queue for the next major release.

**Comment by SwartzCr** [comment]
This is being addressed in #624 :)
as soon as the tests pass we'll merge it, but you'll still have to wait for a new release of Privacy Badger before you get the benefit of it
