### ISSUE TITLE
tracking me when I go to file:///

### ISSUE THREAD

**Issue by pwl42** [EFForg/privacybadgerchrome#592]
Privacy Badger is telling me (after I have clicked the button) that I am being tracked when I browse files in my own filesystem (my home page is on my disk drive).   Is this correct?
Is there a way to automatically block any entity that does this?

**Comment by cooperq** [comment]
can you send me a screenshot of the privacy badger popup on such a file?

**Comment by pwl42** [comment]
before.png is a screenshot that was taken while reading your email.  I immediately went to file:/// and took the after.png screenshot.  the tracking continues as I navigate files on my filesystem.  
 

On the internet nobody can hear you being subtle.   --Linus Torvalds

--------------------------------------------
On Mon, 8/31/15, Cooper Quintin <notifications@github.com> wrote:

 Subject: Re: [privacybadgerchrome] tracking me when I go to file:/// (#592)
 To: "EFForg/privacybadgerchrome" <privacybadgerchrome@noreply.github.com>
 Cc: "pwl42" <pwl42@yahoo.com>
 Date: Monday, August 31, 2015, 2:10 PM
 
 can you send me a screenshot of
 the privacy badger popup on such a file?
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by cooperq** [comment]
Can you embed the screenshots in github instead of sending them as attachments please?
