### ISSUE TITLE
PB dropdown is too short and narrow

### ISSUE THREAD

**Issue by maranomynet** [EFForg/privacybadgerchrome#594]
The drop-down list of 3rd party (tracker) domains is...

1. ...too narrow so domain-names get needlessly truncated and it becomes impossible to determine what 1st-level domain it belongs to.
2. ...too short so even a modest list of domains requires scrolling and multiple screen-shots when communicating with others.

Please make the dropdown flexible - or at least resizable.

**Comment by cooperq** [comment]
We can't make it resizable, and I'm pretty sure we can't make it flexible, but I will look into it. 
Related: EFForg/privacybadgerfirefox#565

**Comment by nextLane** [comment]
Hi, would it be a good idea to give the entire domain-name as a tooltip instead of the present tool-tips that essentially elaborates on meaning of green, yellow and red  levels.

**Comment by cooperq** [comment]
Perhaps, yes!
