### ISSUE TITLE
Sub-domain white list not working

### ISSUE THREAD

**Issue by ZhuDaHai** [EFForg/privacybadgerchrome#595]
If I white-list a top level domain, its sub-domains should also be white-listed, but they are not.
Example:
I white-listed: taobao.com
However, nikor.taobao.com breaks and only works if I white-list it as well.
There are dozens and dozens of subdomains in taobao.com to white-list all of them. I've been at it for a week now, and still finding new ones - and they all break with PB.

**Comment by cooperq** [comment]
when you say whitelisted, how  are you doing the whitelisting?

**Comment by ZhuDaHai** [comment]
Yes, I manually added taobao.com to the white list entries.

**Comment by cooperq** [comment]
did you do it by moving the sliders or adding it to the text box? The text box is a list of domains where privacy badger will be disabled *if that domain is first party* so for example if you were to visit taobao.com directly. To whitelist them as a third party you need to move the slider for that domain in the options page from red or yellow to green.
