### ISSUE TITLE
German translation to Long

### ISSUE THREAD

**Issue by wolffc** [EFForg/privacybadgerchrome#600]
The Message "The Domains below seem to Track you" is to Long in German
and it Wraps out of its Gray Block. i suggest changeing the the Gray Block to a Block of Variable Height. to handle Any Ammount of Text.

![privacy-badger](https://cloud.githubusercontent.com/assets/1393783/9707112/3e9ee8b0-5539-11e5-934c-0a26e915233b.PNG)

**Comment by SwartzCr** [comment]
haha, seems reasonably bad
I guess we should either make the font size dynamic or the size of that div dynamic/larger
I'll try to do this tomorrow

**Comment by wolffc** [comment]
I Just Provided a fix for this Isse See the Pull request https://github.com/EFForg/privacybadgerchrome/pull/607

**Comment by SwartzCr** [comment]
Great! Thanks so much for the pull request. We're currently dealing with some re-licensing issues for PB so we don't want to take outside contributions until we have that figured out. As soon as that's dealt with we'll be happy to merge this, but for now we have to wait on it for a little bit.
I hope that's okay, and thanks so much for submitting the change!

**Comment by wolffc** [comment]
Hi you can consider my Contribution as "Public Domain" i wave all my rights.
Therefore it should not be a Problem in any Licence Change in the Future.

i hardly Think a change from "20px" to "auto" is Protectable by any copyright anyway.

Regards chris
