### ISSUE TITLE
Use storage.sync API to store settings

### ISSUE THREAD

**Issue by ianwalter** [EFForg/privacybadgerchrome#601]
* https://developer.chrome.com/extensions/options
* https://developer.chrome.com/extensions/optionsV2

As the page suggests:
"Always use the storage.sync API to persist your options. This will make them accessible from script within your extension, on all of your user's devices."

**Comment by SwartzCr** [comment]
are you saying that this will sync privacy badger settings across user accounts in chrome?
If so I think this is a policy question that we need to untangle

**Comment by ianwalter** [comment]
Yes exactly. It could be a setting to enable this if that's preferable, but it would be a really nice feature when you're using multiple computers or setting up a new computer and have forgotten to export/import your settings.

**Comment by SwartzCr** [comment]
@cooperq @pde I'd really like you to weigh in on this. On the one hand sharing info with google could be a serious privacy concern, on the other if it's opt in it could be of use to PB users.

**Comment by cooperq** [comment]
So the google privacy concern is definitely one aspect. Another aspect is that storage.sync has a really low limit on the amount of data that can be stored, at ~100 KB. This is less space than we actually use (based on my browser) and I think it would take a major refactor to fit in the space alloted. For that reason I do not think that we should switch to using storage.sync.  Maybe a better option would be a way for users to export and import their data as a JSON dump. This would probably need to be a consistent format between chrome and firefox to avoid confusion.
