### ISSUE TITLE
load times for dpreview.com and wunderground.com >10s

### ISSUE THREAD

**Issue by piccolbo** [EFForg/privacybadgerchrome#604]
Just picking two sites where the difference with badger is staggering. Absolutely unusable.

**Comment by SwartzCr** [comment]
I'm going to close this in favor of #629 which will hopefully fix most slowness issues

**Comment by piccolbo** [comment]
Good programmers let the reporter close.

**Comment by piccolbo** [comment]
Relation with #629 is speculative at best.
