### ISSUE TITLE
Blocking cdn.rawgit.com breaks bountysource.com

### ISSUE THREAD

**Issue by KommX** [EFForg/privacybadgerchrome#611]
Example:
https://www.bountysource.com/issues/26841285-become-the-most-popular-online-chess-server

**Comment by sam5125** [comment]
The tracker cdn.rawgit.com does not exist anymore on https://www.bountysource.com/ . It is most probably replaced by cdnjs.cloudflare.com which is not being blocked by privacy badger.

**Comment by cooperq** [comment]
That does indeed seem to be the case! Thanks!
