### ISSUE TITLE
chrome.exe does not terminate

### ISSUE THREAD

**Issue by andrewscott914** [EFForg/privacybadgerchrome#615]
I noticed that Task Manager was showing increasing numbers of unterminated instances of chrome.exe. I eventually eliminated this problem by disabling Privacy Badger. Windows 7.

**Comment by cooperq** [comment]
It doesn't seem like we should be able to cause this behavior in chrome. We are probably triggering a chrome bug somewhere.

**Comment by andrewscott914** [comment]
Thanks, Cooper.

Date: Fri, 2 Oct 2015 09:03:37 -0700
