### ISSUE TITLE
cbs.com videos don't play when pubads.g.doubleclick.net is blocked

### ISSUE THREAD

**Issue by zekefarwell** [EFForg/privacybadgerchrome#620]
cbs.com refused to play videos and gave an error message saying something to the effect of "A message from our sponsors couldn't be loaded.  Please disable any ad blocking extensions".  Not really a bug with Privacy Badger since cbs.com is actively trying to prevent the use of adblockers, but this is the only place I found to post what I found.  Setting pubads.g.doubleclick.net to only block cookies allowed videos to play.  Would be great if there was an option to allow a tracker only on certain domains -- i.e.  allow  pubads.g.doubleclick.net when visiting cbs.com, but continue blocking it everywhere else.

**Comment by SwartzCr** [comment]
Interesting. Well we're definitely not going to add double click to our cookie block list exceptions list. so I've opened a new issue for the feature request that you mentioned (#622). Feel free to leave more feedback there, and I'm going to close this issue.
