### ISSUE TITLE
Pubnub URL blocked for real-time events

### ISSUE THREAD

**Issue by tylergo** [EFForg/privacybadgerchrome#621]
Hi guys,

I develop a web-app and also use your extension for our general browsing.  Currently Privacy Badger is blocking pubnub (screenshot: http://take.ms/W4SWu), the service we use for our real-time user-to-user messaging.  I highly doubt many of our users have privacy badger, but I'm sure many other web apps use Pubnub, so just wanted to give you guys a heads up.  

This is not a high priority issue.

**Comment by SwartzCr** [comment]
Interesting, do you think you can find us a privacy policy for them, if so it'd make it easier to add them to the cookie-blocklist

**Comment by tylergo** [comment]
I figure it got flagged because I was testing across multiple dev environments. In any case, here ya go: https://www.pubnub.com/privacy-policy/

**Comment by brendanvg** [comment]
I reviewed Pubnub's privacy policy and took issue on a few points:

"PubNub does not respond to ‘Do Not Track’ brower signals or other mechanisms. Third parties may collect personal information about your online activities over time and across sites when you visit the Site or use the PubNub Service."

 "Retention. PubNub retains Customer Information for a period of five (5) years after you cease using the PubNub site."

"Required by Law. PubNub reserves the right to use or disclose information provided if required by law or if we reasonably believe that use or disclosure is necessary to protect our rights ..."

5. Third Party Service Providers.  --does not enumerate what these third parties are....
"Third party service providers that we use are required to protect all data provided hereunder as PubNub confidential information, restricting transfer and disclosure to any other third party." -it is unclear what the specific restrictions are that pubnub gives to thirdparties on how/what they are able to share with other third-parties?

**Comment by cooperq** [comment]
For the reasons that @brendanvg describes above I am not comfortable with unblocking pubnub.
