### ISSUE TITLE
Top level menu message should tell the user that they don't need to mess with sliders unless things are broken.

### ISSUE THREAD

**Issue by pde** [EFForg/privacybadgerchrome#627]
From doing some usability evaluation withe Ane from Simply Secure:

Make the top level narrative message in the Privacy Badger menu be, "You don't need to mess with these settings unless something is broken."

**Comment by pde** [comment]
Possible language:

"Every time you visit a new site, Privacy Badger learns about what to block. Load some more sites to make it smarter! You shouldn't need to use this menu unless something is broken."

**Comment by SwartzCr** [comment]
We could add a div much like the one that says "These third parties don't appear to be tracking you" above all the listed third parties that has this text.

**Comment by cooperq** [comment]
I think we should just add this language to the end of the `These sliders let you control how Privacy Badger handles each one.` text.

**Comment by sam5125** [comment]
Should the overall message be like:
These sliders let you control how Privacy Badger handles each one. These third parties don't appear to be tracking you.

or some other changes are expected.

**Comment by SwartzCr** [comment]
I believe the current solution is to add the text 'You shouldn't need to adjust them unless something is broken." to the end of the text that currently reads: "Privacy Badger detected 0 trackers on this page. These sliders let you control how Privacy Badger handles each tracker."
It should not be added to the section that says "The domains below don't appear to be tracking you"
