### ISSUE TITLE
Consider making the red number be meaningfully gameable

### ISSUE THREAD

**Issue by pde** [EFForg/privacybadgerchrome#628]
Cecause Privacy Badger gets smarter over time, we could make the red "blocked" number in the UI be something that is strictly increasing as PB works better.

(This is a suggestion from a UI test... I'm *not* sure if there's a good way to do it)

**Comment by SwartzCr** [comment]
Well notably the number could reflect the number of blocked trackers, as opposed to the number of noticed trackers. This wouldn't be hard to implement if that's what we decided to do

**Comment by jawz101** [comment]
Take a look at this idea.  I'd have to draw it on paper I suppose https://github.com/EFForg/privacybadgerfirefox/issues/561

**Comment by cooperq** [comment]
+1 I think that the way to do this is what @SwartzCr said. We could combine this with increasing the number of hits for a given third party domain, which could be shown in the options page.

**Comment by cooperq** [comment]
fixed in #650
