### ISSUE TITLE
widgets.ellentube.com

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadgerchrome#632]
Breaks video:

http://www.cosmopolitan.com/entertainment/a47503/selena-gomez-ellen-degeneres-revival-appearance/
http://www.elle.com/culture/celebrities/news/a31074/selena-gomez-ellen-degeneres-revival-appearance/
http://perezhilton.com/2015-10-09-selena-gomez-ellen-degeneres-lupus-body-shamers-dating
http://ellentube.com/videos/0-bwxcoi54/

**Comment by cooperq** [comment]
Not whitelisting this one: 
> We may disclose personally identifiable information about you to companies whose practices are not covered by this Privacy Policy. For example, we may share such information we collect with our affiliates to provide, improve and communicate with you about their own products and services.
> 
>We may also share such information with business partners and third parties (e.g., other marketers, magazine publishers, retailers, participatory databases and non-profit organizations) that want to market products or services to you. If we share personally identifiable information with such unaffiliated third parties for their own marketing purposes, we will provide you with an opportunity to opt out or block such uses.
Pretty bad privacy policy, I think this one should just be allowed by users if they want it.
