### ISSUE TITLE
bandcamp.com should be on yellowlist

### ISSUE THREAD

**Issue by Be-ing** [EFForg/privacybadgerchrome#640]
Some musicians have their own domains hosted by Bandcamp, so Privacy Badger learns to block bandcamp.com. However, this brakes the websites. I was unable to play music on Bandcamp's web player or purchase music until I manually moved the bandcamp.com slider to the yellowlist.

**Comment by cooperq** [comment]
Totally okay with this.

**Comment by cooperq** [comment]
fixed by #654
