### ISSUE TITLE
Chrome does not permit Privacy Badger options changes and crashes

### ISSUE THREAD

**Issue by IkonRahu** [EFForg/privacybadgerchrome#643]
Google Chrome does not permit changes to Privacy Badger options. Changing slider controls for blocking cookies and domains are not saved. Attempting to change several tracking domains crashes Privacy Badger and renders it unusable until browser restart or extension reload. New tab on browser inoperable, status bar message "Waiting for Privacy Badger extension...". Google mail buttons unreadable. 

Google Chrome Version 46.0.2490.80 m
Windows 7 Home Premium SP1
Browser settings: Allow local data to be set; block third-party cookies and site data.

**Comment by Kinnera323** [comment]
I have been using the privacybadger on the same version of google chrome on Ubuntu 14.04 LTS, but I never found such problem. May be try reinstalling chrome and try the same. If the problem still exists, put a screenshot with a clear description of the problem.

**Comment by charlesprogrammr** [comment]
I can confirm this issue, have been fighting it for months. It might be mitigated, if we could get a save button on the configuration page and save incrementally. I've tried with as low as 8 changes per go, but when you finish and it isn't finished, you can not tell, so even with a small number of changes, there is no way to tell if/when they are saved, and closing the browser will stop the save. It's frustrating.

**Comment by cooperq** [comment]
@charlesprogrammr @IkonRahu can you give me an exact set of steps to reproduce this problem?

**Comment by cooperq** [comment]
This should be fixed here: https://github.com/EFForg/privacybadgerchrome/wiki/Help-test-Privacy-Badger-for-chrome
