### ISSUE TITLE
music.yandex.ua, music.yandex.ru should allow subdomains of yandex.net

### ISSUE THREAD

**Issue by skfd** [EFForg/privacybadgerchrome#646]
Yandex serves music from subdomains of `yandex.net`. Normally it may be considered tracking site, but we're already on company's site.

P.S. Is there some specialised place to report and track site-bugs? It would be nice to have `privacybadger-core` or `privacybadger-db`.

**Comment by cooperq** [comment]
this is a fine place to report site bugs. This can probably be solved by adding yandex domains to the cookie block list.
