### ISSUE TITLE
kaltura rule blocks video

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadgerchrome#655]
http://thefreethoughtproject.com/high-school-student-tackled-officers-phone-call-sick-mother/

Video is blocked by `cdnapi.kaltura.com`, `cdnbakmi.kaltura.com`, and `www.kaltura.com`. I understand it's a tracker, but I thought it should be brought to your attention.

**Comment by cooperq** [comment]
I am unable to test this since playing the video requires flash. I wonder if this can be fixed by moving certain kaltura.com subdomains to cookieblocked. @terrorist96 can you test this and see what the minimum number of subdomains that would need to be added to the cookieblock list would be to fix this?

**Comment by hansika** [comment]
@terrorist96 When I checked this URL, the domains were not blocked by Privacy Badger by default and I could play the video with no problem. But of course when I moved the sliders of the aforementioned domains to blocked state, the video got blocked.

**Comment by terrorist96** [comment]
The following have to be moved to yellow to get the video to load:

cdnapi.kaltura.com
cdnbakmi.kaltura.com
www.kaltura.com

@hansika Yes, they weren't blocked for me initially either, but as I browsed around, and came back to that page, then it was blocked because PB realized it's a tracker.

**Comment by hansika** [comment]
@terrorist96 yes. that's true. I sent a pull request after including the above domains in the yellowlist. The request has been merged.

**Comment by terrorist96** [comment]
Thanks!
