### ISSUE TITLE
shopping functionality being blocked

### ISSUE THREAD

**Issue by zaid-foodity** [EFForg/privacybadgerchrome#678]
Hello,

Our shopping tools functionality, which is being used by dove.co.uk, bbcgoodfood.com, jamieoliver.com and other household names, are being blocked by Privacy Badger.

This functionality allows a user to populate their shopping basket at a retailer's site directly from the brand/publisher's site.

Can *.constant.co and *.foodity.com please be added to the yellow list?

Many thanks,
Zaid

**Comment by cooperq** [comment]
I'm sorry but I cannot add you to the Yellowlist. To be unblocked by privacy badger you must adopt our Do Not Track policy (and actually do what it says). The do not track policy can be found here: https://eff.org/dnt-policy
If you adopt the DNT Policy and implement it privacy badger will not block your content.
