### ISSUE TITLE
Privacy badger vs facebook

### ISSUE THREAD

**Issue by dzila** [EFForg/privacybadgerchrome#690]
Hi,

This may not actually be a bug. I have recently installed Privacy badger. Soon after doing that facebook reported I have malware in my computer and prevented me from posting. After I downloaded its malware detection tool and ran it, it reported it discovered and deleted some generic malware. I think it was privacy badger because I discovered after that, it was broken in chrome. I had to reinstall it.

I am not sure how I should deal with this problem. Any suggestions are welcomed. Thanks.

**Comment by cooperq** [comment]
Strange indeed! Now that you have reinstalled privacy badger can you run the malware detection tool again and see what happens?

**Comment by dzila** [comment]
Hi,

I just retried, again with the ESET tool that facebook suggested. This time it reported no malware, but privacy badger is again broker after running it and restarting chrome.

**Comment by dzila** [comment]
ESET versions are ESET_T10153893592448643T_ and ESET_T10153896299728643T_

**Comment by cooperq** [comment]
Unfortunately I don't think there is anything we can do about this, we should try to get in touch with facebook security and file a bug report with them.

**Comment by dzila** [comment]
Hi I waited for facebook to unblock me with privacy badger removed by their malware detection tool. I just reinstalled privacy badher to see if I get blocked again.

**Comment by cooperq** [comment]
I bothered them on twitter here: https://twitter.com/PrivacyBadger/status/668895741822107648 lets see if they get back to us.

**Comment by dzila** [comment]
Still running privacy badger and facebook without any issues.

**Comment by cooperq** [comment]
closing for now.
