### ISSUE TITLE
Problems on OpenStreetMap

### ISSUE THREAD

**Issue by KommX** [EFForg/privacybadgerchrome#695]
PrivacyBadger shouldn't block (a|b|c).tile.thunderforest.com because then www.openstreetmap.org is unusable.

**Comment by cooperq** [comment]
Can you help me reproduce this? I don't see those domains being loaded at all.

**Comment by KommX** [comment]
1. Visit https://www.openstreetmap.org
2. Click the "Layers" button on the right-hand side.
