### ISSUE TITLE
http-only third party site that tracks: PB can't read its dnt policy

### ISSUE THREAD

**Issue by PollyP** [EFForg/privacybadgerchrome#702]
Before PB adds an origin to the blocklist, it calls checkPrivacyBadgerPolicy to look for a posted dnt-policy.txt file on the site, using https. If the site supports https and the file's not there, the xhrRequest quickly 404s out, the function is exited, the blocklist is updated, and the UI reflects this new state. All good.

But if the site is http only, the xhrRequest does not come back until the connection request times out (around 75 seconds on my machine). During this time, the UI continues to report the stale origin state.

**Comment by PollyP** [comment]
Another, and more troubling, aspect of this bug is if the third party site does have a dnt policy file but serves http only, PB will never see it and will go ahead and block the site. I've edited the bug title to emphasize this point.

**Comment by michael-oneill** [comment]
The EFF DNT policy Url has to use https 

 

From https://www.eff.org/dnt-policy :

3.b. ensure that the operators of those domains abide by this policy overall

     by posting it at /.well-known/dnt-policy.txt via HTTPS on the domains in

     question,

 

Though I agree the PB XHR shouldn’t wait for the completion.

**Comment by PollyP** [comment]
Good point; I missed that requirement.

**Comment by cooperq** [comment]
Polly, since the code is working as expected (not recognizing DNT without https) is there still a bug here?

**Comment by PollyP** [comment]
I'd demote this from a bug to an enhancement request. :)

When I encountered this, though, I really did think PB was broken, because it took so long for the UI to update. I wonder if it appears that way to others, too.  What about adding a timeout to the XmlRequest()?

**Comment by cooperq** [comment]
Adding a timeout to the xmlRequest seems like a good solution to me!
