### ISSUE TITLE
Privacy Badger Alert (3rd party request) is obtrusive and unintuitive

### ISSUE THREAD

**Issue by molenick** [EFForg/privacybadgerchrome#708]
I just got a "Privacy Badger Alert" which is blocking access to an entire page I requested in Firefox.  It's giving me two options: 1) To permanently allow or 2) to permanently prohibit soundcloud from loading third party content.

GIven that I'm just trying to read someone's blog, I don't want to make such a hefty decision about the future of Soundcloud's 3rd party access right this moment.  I think following Firefox's model for 3rd party plugins (like Google Talk) would be better since it gives a person the ability to make a longterm choice (block/allow forever) or a short term choice (block/allow for this session).  Additionally, the [X] in the top right corner of the window doesn't do anything.

I prefer this short term scheme because I prefer plugins/3rd party content to be blocked by default, but if I really need to see something it I can grant it one time access.  Thanks for listening, and thanks for making Privacy Badger!

Here's a link to the page I encountered this on: http://jeremylimmusic.com/legal/how-my-music-was-plagiarized-for-profit-and-how-i-fought-back-joseph-ti-into-the-deep/

**Comment by cooperq** [comment]
In chrome we are able to have an option that says 'allow [tracking domain] for this site only' which I think is a good solution. At the time when I wrote this feature in firefox doing such a thing was not possible but I think that now it is.

**Comment by molenick** [comment]
Cool, thanks!  Mostly what I took issue with was that I had to make a "permanent" setting without being able to cancel out or really see the context that is was loading in the page.

**Comment by chepec** [comment]
I was just googling this after encountering this popup a few times over the last few weeks, good to see it's being handled. Great, in fact.

So far I've always encountered this popup while reading my RSS reader (tinytinyrss, in Firefox btw) and whatever choice I made always caused the session to reload which was very annoying.

**Comment by cooperq** [comment]
I think that the best solution here is to replace this with a button like how we do social widgets. Tracking this in #400
