### ISSUE TITLE
google-analytics breaks video on insider.foxnews.com

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadgerchrome#710]
http://insider.foxnews.com/2015/12/16/mistrial-declared-freddie-gray-case-judge-napolitano-reacts-shepard-smith-reporting

google-analytics.com needs to be moved to yellow to fix video.

**Comment by cooperq** [comment]
I think that a good solution for this sort of problem is to implement #400

**Comment by cooperq** [comment]
I am definitely not comfortable with adding google-analytics to the cookie block list.

**Comment by terrorist96** [comment]
So any news on script surrogates? I don't like setting google analytics to yellow either, but I have to in order to video videos on insider.foxnews.com.

**Comment by terrorist96** [comment]
ssl.google-analytics.com triggers an adblock warning on wired.com
http://www.wired.com/2016/01/game-life-podcast-oxenfree/

**Comment by cooperq** [comment]
I think I finally have a good solution for how to implement script surrogates and it is now one of my top priorities.

**Comment by terrorist96** [comment]
Forget about ssl.google-analytics.com breaking wired.com. Seems like they changed their detection trigger from analytics to google adsense.

**Comment by cooperq** [comment]
:( boooo wired. but okay this is still on my list.

**Comment by terrorist96** [comment]
> http://insider.foxnews.com/2015/12/16/mistrial-declared-freddie-gray-case-judge-napolitano-reacts-shepard-smith-reporting

Looks like this is now working with analytics being blocked.

**Comment by cooperq** [comment]
In that case I'm going to close this issue in favor of #400
