### ISSUE TITLE
abc7news.com video broken

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadgerchrome#718]
http://abc7news.com/politics/tensions-boiled-over-gun-control-during-democratic-debate/1129217/

Video won't load. Tried setting everything to yellow but still wouldn't load. I disabled PB from the extensions page and the video worked. No idea what is breaking it.

**Comment by terrorist96** [comment]
uplynk was what was breaking it.
https://github.com/EFForg/privacybadgerchrome/issues/738

**Comment by cooperq** [comment]
closing in favor of #738
