### ISSUE TITLE
badger with block: flash & html5 video

### ISSUE THREAD

**Issue by zlotowinfo** [EFForg/privacybadgerchrome#727]
chrome is stupid browser, every more plugin consume more memory
i use privacy badger all time

id like to badger have that two new option:
- block flash
- block html5 player (or totaly block html5)

**Comment by cooperq** [comment]
Thanks, and I am glad you like using Privacy Badger! 
As for the features you requested:
Blocking flash is already built into chrome, there is no need for us to duplicate this functionality. 
Blocking HTML5 video is not an option I am interested in adding, there may be other extensions which do this, but it is not in line with privacy badger's goals of blocking trackers. 

Thanks for the suggestions!

**Comment by zlotowinfo** [comment]
its bad i hear it, in that situation think adblock offer better functionality
