### ISSUE TITLE
fonts.com does not work... and they seem like they don't know it.

### ISSUE THREAD

**Issue by syeo66** [EFForg/privacybadgerchrome#729]
Maybe you have more possibilities to help them with this issue. There answer:

"Hello,

Thank you for contacting us and I apologize for the reply in English. By default, none of the content from our Fonts.com website or web font service triggers any warnings or blockings in Privacy Badger. If you are having difficulty, please let us know more information.

Best Regards,"

While I see this:

![bildschirmfoto 2016-01-20 um 17 10 44](https://cloud.githubusercontent.com/assets/1178021/12454914/c62ac022-bf99-11e5-802d-f31ea4b9ce05.png)

**Comment by cooperq** [comment]
Interesting, so for me fonts.net is not seen as a tracker at all by privacy badger (it is under the list of things not tracking you.) If you look at your cookies can you see any cookies from fonts.net? For now I think this is an edge case and of course the best fix for you is to unblock fonts.net

**Comment by syeo66** [comment]
Well, I guess the point is that Privacy Badger might see it as a tracking page as soon as you visit some webpages which use their webfonts.

**Comment by cooperq** [comment]
Can you give me an example of a page that uses fonts.net for fonts?

**Comment by cooperq** [comment]
For now the issue can be fixed by moving fonts.net to yellow or green.

**Comment by syeo66** [comment]
My website is using their fonts: http://redochsenbein.ch/ or http://www.worldoftone.ch/ would be another example. Yes, manual adjustments works for now.

**Comment by cooperq** [comment]
Fonts.net does not appear to be setting any cookies for me. But I have added it to the cookieblock list anyway so that no one else will have this problem. Fixed in 56f7a28
