### ISSUE TITLE
chat.online.citi.com broken

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadgerchrome#735]
So, attempting to initiate a chat session from Best Buy's credit card service will not work when Privacy Badger is active. The worst part is that since the chat opens in a new window, Chrome extensions aren't visible, so they can't be toggled and I can't see what PB rule is causing the chat window to not load. All I know is that when I deactivate PB from Chrome's extension menu, the chat will load.

Here's a link to the chat window, but it might not be very helpful; I've X'ed out any keys:

https://chat.online.citi.com/hc/74943702/?cmd=file&file=chatFrame&site=74943702&visitor=XXXXXXXXXXXXX&msessionkey=XXXXXXXXXXXXXXXXX&siteContainer=STANDALONE&LEAppKey=XXXXXXXXXXXXXXXXXXXXXXXX&SV!chat-button-name=chat-BBY-general-english&SV!chat-button-room=chat-BBY-general-english&referrer=(button%20dynamic-button:chat-BBY-general-english(Best%20Buy%20Credit%20Card%3A%20Home))%20https%3A//citiretailservices.citibankonline.com/RSnextgen/svc/launch/index.action%3FsiteId%3DPLCN_BESTBUY%26langId%3Den_US%26pagename%3Dauthenticate%23makepaymentoptions&sessionkey=XXXXXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXX

**Comment by cooperq** [comment]
Perhaps you could open a console by hitting F12 and open the network tab to see what domains are getting blocked?

**Comment by terrorist96** [comment]
There's two different things in the network tab. One keeps repeating (which I think would indicate it's being blocked) and one appeared just once.  The repeating one is: 

> https://chat.online.citi.com/api/account/74943702/js2rest/chat?lpV=1&lpjson=1&lpB=%7B%22u%22%3A%22https%3A%2F%2Fchat.online.citi.com%2Fapi%2Faccount%2F74943702%2Fcollaboration%2F1fc23704-4941-4610-8e2a-1040c1e38d12%2Fevents%3Ffrom%3D0%26v%3D1%22%2C%22m%22%3A%22GET%22%2C%22h%22%3A%7B%22AUTHORIZATION%22%3A%22LivePerson%20appKey%xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx%22%7D%2C%22b%22%3A%7B%7D%7D&cb=xxxxxxxxxxxxxxxxx$xxxxxxxxxx

and the one that appeared just once is:

> https://chat.online.citi.com/hc/74943702/?lpCallId=3280913810201505789-3693717977&protV=20&lpjson=4&site=74943702&cmd=requestConfig&ccn=LPChatAPINS

The initiator for both is core.min.js

Please let me know what else you need. I was going to paste the HAR for each, but it would be way too long. I could email it to you if you like.

Thanks

**Comment by terrorist96** [comment]
After some more testing with the latest version of PB, it seems like it's Ghostery that's actually causing it to fail.
