### ISSUE TITLE
Insecure loading of local /skin/socialwidgets.css

### ISSUE THREAD

**Issue by bronwynlewis** [EFForg/privacybadgerchrome#737]
This may be a non-issue (since it's against a local file), but just came across this while poking at Chrome's devtools security update.

It appears the following is accessed via an insecure call from the PB extension:
chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/skin/socialwidgets.css

Disabling the Social Widget Replacement in PB's settings stops that insecure call from being made.

**Comment by cooperq** [comment]
Do you mean insecure as in it doesn't go over https? I think this is a non-issue since it is loaded locally from the browser itself.

**Comment by doweio** [comment]
Not sure if this thread is too old to comment on, but I have just had the same happen to me.

It's a problem when you have browsed a previously non-secure location - for example, a website over HTTPS using an invalid certificate.  If this same site then has a valid security certificate installed, the socialwidgets.css file still seems to load in a non-secure way, invalidating the entire SSL connection in Chrome.
