### ISSUE TITLE
uplynk.com breaks video

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadgerchrome#738]
http://wwmt.com/news/local/new-legislation-would-allow-concealed-carry-without-a-permit

Need to move the following to yellow in order to fix video:
content.uplynk.com
content-aeui1.uplynk.com
stg-ec-ore-u.uplynk.com

**Comment by cooperq** [comment]
I am unable to test this because I don't have flash enabled. I believe your solution would work though. The problem is that uplynk is definitely being used to track and serve targeted ads. I would not be suprised to learn that they use flash LSO's to track, which our cookie blocking does not currently prevent. I am unable to find any privacy policy for uplynk either. 
Right now I am not comfortable with adding uplynk to the yellow list at this time.

**Comment by cooperq** [comment]
Perhaps I would be comfortable adding them to the yellow list if we added functionality to block LSOs

**Comment by cooperq** [comment]
Actually this seems like a really good candidate for #400

**Comment by terrorist96** [comment]
Just posting another example:

http://abc30.com/news/fresno-law-enforcement-leaders-speak-out-against-proposed-gun-control-measure/1342975/#videoplayer

storage, content, content-ausc2, and stg-ec-ore-u.uplynk.com all need to be yellowlisted to fix the video.

**Comment by terrorist96** [comment]
http://fox23maine.com/news/local/nra-takes-aim-at-question-3-in-maine

To fix video, yellowlist:
`content.uplynk.com`
`content-aeuf2.uplynk.com`
`stg-ec-norcal-u.uplynk.com`

**Comment by terrorist96** [comment]
http://wgme.com/news/local/no-on-3-sign-vandalized-in-york-county

The following need to be on the yellowlist to fix the video:
`content.uplynk.com`
`content-aeuf1.uplynk.com`
`stg-ec-ore-u.uplynk.com`

**Comment by alexristich** [comment]
@cooperq Should `uplynk.com` be added to the cookieblock list? Looks like it's a CDN which is owned by Verizon, so seems like a good candidate.

**Comment by cooperq** [comment]
Sure. @alexristich can you submit a pull request?

**Comment by terrorist96** [comment]
@cooperq I took care of it.
#943 and #944

**Comment by terrorist96** [comment]
Can you confirm if I did it right? Do I have to edit both the regular and legacy files? Does a separate PR need to be done for the FF version?

**Comment by cooperq** [comment]
@terrorist96 you did it right! You do need to edit both files, you do not need a seperate PR for firefox. good job, and thanks!
