### ISSUE TITLE
Blocking www.img-bahn.de breaks bahn.de

### ISSUE THREAD

**Issue by KommX** [EFForg/privacybadgerchrome#739]
When www.img-bahn.de is blocked:

1. Go to bahn.de
2. Search for a connection on the left.
3. Hit "suchen"

Result:

![bahn de](https://cloud.githubusercontent.com/assets/7859245/12831117/ee5199f4-cb92-11e5-8803-081b079b81aa.png)

**Comment by cooperq** [comment]
added to cookeiblock list.
