### ISSUE TITLE
cfvod.kaltura.com breaks video

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadgerchrome#743]
http://www.clickondetroit.com/news/dearborn-heights-isis-supporter-planned-to-attack-detroit-church

`cfvod.kaltura.com` needs to be yellow for the video to play.

Kaltura was previously moved to the cookie block list without issue [here](https://github.com/EFForg/privacybadgerchrome/issues/655) so this should be an easy fix, right?

**Comment by cooperq** [comment]
fixed in 4561161
