### ISSUE TITLE
tkx2-prod.anvato.net breaks video

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadgerchrome#756]
`tkx2-prod.anvato.net` breaks the video here:
http://nbc4i.com/2016/03/01/town-sign-warns-criminals-this-is-not-a-gun-free-zone/

Needs to be set to yellow for it to work.

**Comment by terrorist96** [comment]
Another example: http://www.whsv.com/content/news/Constitutional-Carry-Bill-Defeated-in-Virginia-Senate--367304011.html

**Comment by cowlicks** [comment]
In addition to `tkx2-prod.anvato.net` I needed to set `up.anv.bz` to yellow for the videos to work.

**Comment by cowlicks** [comment]
For the second link, in addition to the above links, I had to set `mcp-media5.cdn.anvato.net` to get the video to work.

**Comment by terrorist96** [comment]
> For the first link, in addition to tkx2-prod.anvato.net I needed to set up.anv.bz to yellow for the videos to work.

`up.anv.bz` is green by default for me. Maybe it hasn't tried tracking me yet.

> For the second link, in addition to the above links, I had to set mcp-media5.cdn.anvato.net to get the video to work.

I can confirm this.

Also, another example: http://www.fox5ny.com/news/100475345-story

**Comment by cowlicks** [comment]
I can make a PR to fix these, but I'm not sure if they meet the [yellowlist criteria](https://github.com/EFForg/privacybadgerchrome/blob/master/yellowlist-criteria.md).
* [ ] Was this in [Bau and Mayer's](https://jonathanmayer.org/papers_data/bau13.pdf) manually curated non-tracker list?
* [x] Is this domain necessary for functionality the user expects from 1st party pages?
* [ ] Is the domain's privacy policy clear that it does not perform non-consensual tracking?
* [ ] Is there a reasonable self-hosted surrogate available that could replace the functionality of this domain (e.g.    https://github.com/EFForg/privacybadgerchrome/issues/400).

**Comment by terrorist96** [comment]
@cooperq @cowlicks 
The following need to be added to the yellowlist as well:

`mcp-media5.cdn.anvato.net`
`mcp-media6.cdn.anvato.net`

http://www.thenewscenter.tv/content/news/Local-counties-see-large-increase-in-concealed-carry-permits--374536591.html

media5 allows the video to play; media6 shows the other videos under 'more video...'

**Comment by cooperq** [comment]
fixed in 25946e3e9ad8826e6fd81469cf6663cba24ebafd
@terrorist96 this sort of thing is generally easy to make a pull request for! I would encourage you to do so if you are familiar with git!
