### ISSUE TITLE
Where is "Bau and Mayer's manually curated non-tracker list"?

### ISSUE THREAD

**Issue by cowlicks** [EFForg/privacybadgerchrome#757]
This list in mentioned in the [yellow list criteria](https://github.com/EFForg/privacybadgerchrome/blob/master/yellowlist-criteria.md), but nothing links to it. There is just a link to a paper.

When the list is located we should link to it from the yellowlist criteria document for easy reference.

**Comment by cooperq** [comment]
All of the domains on Bau and Mayers list have already been included in the cookie block list. That criteria is there to explain why those domains are on the list.
