### ISSUE TITLE
Privacy Badger should merge into a single codebase using WEAPI and removing ABP

### ISSUE THREAD

**Issue by cowlicks** [EFForg/privacybadgerchrome#762]
It seems like there are two mostly independent codebases being developed. Is this the case?

If so, maybe this can change soon. Mozilla is planning on providing an extension API that will be compatible with chrome and opera called  [WebExtension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions). It will be stable [later this year](https://wiki.mozilla.org/RapidRelease/Calendar).

I had some time to try this, so I downloaded the [ff developer edition](https://www.mozilla.org/en-US/firefox/developer/) to test this out, and I started walking through the ["porting from google chrome" guide](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_from_Google_Chrome).

The first problem was that the "unlimitedstorage" permission is not supported in firefox yet. But hopefully we won't need more than the default amount of storage (5mb?) initially. There were a few changes needed to the manifest.json. Then I tried to load the extension to firefox. Basically it didn't work, the PB icon shows up and I can open the menu but it is not blocking anything.

I tried to take a screenshot of the menu, but for some reason the menu disappears when the screenshot happens.
![pb-menu-in-ff](https://cloud.githubusercontent.com/assets/598099/13693612/513ac3b6-e712-11e5-97cd-bf5a6ecd6e16.png)

Here is the settings page
![pb-settings-in-ff](https://cloud.githubusercontent.com/assets/598099/13693614/54a1626c-e712-11e5-9fd6-2694bae985ce.png)

I'm not sure what the next steps to take here would be.

The branch I'm working on is [here](https://github.com/cowlicks/privacybadgerchrome/tree/port-to-ff).

**Comment by rcutmore** [comment]
I've been wondering about this as well.

Is it feasible to migrate from the Firefox version and use that as a combined code base? I'm not sure if it's preferable but it would get rid of the Adblock Plus dependency. Maybe it would be more work than starting with the Chrome version and eventually removing Adblock Plus?

**Comment by cowlicks** [comment]
@rcutmore The work on WebExtensions is to make Chrome extensions mostly compatible with FF. I think it would be a lot more work to make the FF extension compatible with Chrome.

But I forgot about the ABP problem. That dependency would probably have to be removed to get this to work.

**Comment by cooperq** [comment]
So, this task is actually my top priority for Privacy Badger right now. Indeed having two codebases creates twice the work for myself and anyone else who wants to contribute to the project. I have thought a lot about this and I think that removing the adblock plus dependency and making the necessary modifications to the chrome codebase to work with WEAPI is the correct choice.  I think that I will start a branch called WEAPI that we can work in while we make this transition and make a set of issues that can cover the large tasks that need to be done for this to happen.
If either of you are interested in helping with this task it would be hugely appreciated! 
 Here are the large tasks as I see them:

1. Create a new storage engine for privacy badger (seperate from abp infrastructure)
2. Switch code to using new storage engine 
3. Write code to migrate privacy badger data from ABP data store to new data store
4. At this point we have to do a release so everyone can get their data migrated to the new engine
5. Remove all adblockplus code (re-implementing any functionality we still need)
6. Begin testing with web extensions API and fix any bugs
7. Another new release for firefox and chrome

**Comment by cowlicks** [comment]
Awesome plan! I have time to work on this so I'll be thinking about where I can help out.

**Comment by cooperq** [comment]
closed by 
as of b27478d03b1b1f2c0a46e89311d31b59f6110f99 the new storage library liiiives!!!
the source and documentation can be found here: https://github.com/EFForg/privacybadgerchrome/blob/weapi/src/storage.js

**Comment by cooperq** [comment]
Privacy Badger has been refactored! Adblock plus is no longer the storage engine!  A new release has been made!
:fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: 
Instructions on how to install the beta of the new release (if you haven't auto updated) live here: https://github.com/EFForg/privacybadgerchrome/wiki/Help-test-Privacy-Badger-for-chrome

**Comment by cooperq** [comment]
Work on #778 and #779 is happening here: https://github.com/EFForg/privacybadgerchrome/tree/firefox-compat

**Comment by cooperq** [comment]
Pull request open for firefox work here: https://github.com/EFForg/privacybadgerchrome/pull/845

**Comment by cowlicks** [comment]
@cooperq I have a lot of free time this week to look at this, where do you think would be a useful place to jump in?

**Comment by cooperq** [comment]
@cowlicks  that's great! The best place to jump in right now is definitely: https://github.com/EFForg/privacybadgerchrome/pull/845

The top items are probably fixing privacy badger in incognito mode and beating on it to make sure there are no more bugs. The second priorities would be anything in the 2.0 milestone

**Comment by cooperq** [comment]
Current To do list:

1. ~~Create a new storage engine for privacy badger (seperate from abp infrastructure)  #767~~
2. ~~Switch code to using new storage engine #775~~
3. ~~Write code to migrate privacy badger data from ABP data store to new data store #776~~
4. ~~At this point we have to do a release so everyone can get their data migrated to the new engine~~
5. ~~Remove all adblockplus code and migration code(re-implementing any functionality we still need), #777~~
6. **(WIP)**Begin testing with web extensions API and fix any bugs #845 
7. **(WIP)**Write code to migrate from legacy pb-firefox storage engine to new storage engine #845 
8. Another new release for firefox and chrome
9. Redirect firefox codebase to new unified codebase on github - update all relevant URLS

**Comment by cowlicks** [comment]
In addition to redirecting pbff to this repo, this repo should also be renamed. The certbot/le folks just did this so they might have some insight.

**Comment by cowlicks** [comment]
Got this installed in Chrome and FF, I'll let you know how it goes.

Can you recommend some pages to visit to get PB to start blocking stuff?

**Comment by yieldman** [comment]
tomsguide.com                                                             
tomshardware.com                                                          
ranker.com                                                                
cracked.com

These domains should train fresh PB enough for testing.
