### ISSUE TITLE
entitlement.auth.adobe.com and sp.auth.adobe.com

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadgerchrome#765]
http://www.adultswim.com/videos/infomercials/icelandic-ultrablue-phase-one/

`entitlement.auth.adobe.com` and `sp.auth.adobe.com` (and `adm.fwmrm.net` #579) have to be yellow to fix video.

**Comment by cooperq** [comment]
added to cookie block list in 1fda4d93fbc4d0ce4b60f8be48fac22e1a7679f7

**Comment by terrorist96** [comment]
@cooperq *.auth.adobe.com still appears red for me on the above site.
