### ISSUE TITLE
Create a new storage engine for privacy badger

### ISSUE THREAD

**Issue by cooperq** [EFForg/privacybadgerchrome#767]
We need a new storage engine which is not dependent on any of the ABP code. This issue will track the design and development of that storage engine.

**Comment by rcutmore** [comment]
I've been thinking about how to approach this. Here are some of the steps I've come up with, though it also encompasses #775.

1. Identify JS files that interact with Adblock Plus and clean up a bit (remove unused functions, commented out code).
2. Write a wrapper around interactions with Adblock Plus and create tests.
3. Start replacing with new storage engine (at this point divide into more manageable steps).

Is there anything I'm missing or is there a better way to approach this?

It looks like the following files in the *src* directory interact with ABP:

- background.js
- heuristicblocking.js
- popup.js
- webrequest.js

*lib/options.js* interacts with it as well (should this be moved to *src*?). I might be missing some.

**Comment by cooperq** [comment]
bringing @SwartzCr into this as well. We just spent the morning coming up with what the new data structure should look like, I have documented this in https://github.com/EFForg/privacybadgerchrome/blob/master/doc/DESIGN-AND-ROADMAP.md

**Comment by cooperq** [comment]
options.js should definitely be moved into src

Also all this work should be happening in the weapi branch, which I have pushed to github

**Comment by cooperq** [comment]
closed by b27478d03b1b1f2c0a46e89311d31b59f6110f99
the new storage library liiiives!!!
the source and documentation can be found here: https://github.com/EFForg/privacybadgerchrome/blob/weapi/src/storage.js
