### ISSUE TITLE
Add list of multi-domain first parties

### ISSUE THREAD

**Issue by catrope** [EFForg/privacybadgerchrome#781]
At the Wikimedia Foundation, we run web sites on a number of different domains that talk to each other and are essentially all the same first party. Privacy Badger recognizes that `en.wikipedia.org` and `de.wikipedia.org` are the same party, but it does not recognize that domains like `commons.wikimedia.org` and `fr.wiktionary.org` are also the same party. This frequently leads Privacy Badger to block AJAX requests from e.g. `*.wikipedia.org` domains to `*.wiktionary.org` domains, which breaks [our unified login system](https://phabricator.wikimedia.org/T108505) and [our new cross-wiki notifications beta feature](https://phabricator.wikimedia.org/T129764).

Putting our domains on the yellow list doesn't help, because these features are closely tied to user identity so they need cookies for authentication to work. Another way we could work around this is by publishing a DNT policy file, but we can't, at least not right now, since we have our own privacy policy that is almost-but-not-quite DNT-compliant (see [relevant policy paragraph](https://wikimediafoundation.org/wiki/Privacy_policy#Our_Response_to_Do_Not_Track_.28DNT.29_signals) and [FAQ  entry](https://wikimediafoundation.org/wiki/Privacy_policy/FAQ#DNTFAQ)).

I've been thinking that other web sites probably have a similar issue. For example, a request from `gmail.com` to `*.google.com` should also be treated as a first-party request rather than a third-party request. For that reason I propose adding a list of groups of domains that all belong to the same party, and have Privacy Badger treat a cross-domain request within the same domain group as a first-party request (i.e. allow it by default).

**Comment by michael-oneill** [comment]
The W3C Tracking Preference Expression document (TPE) defines a same-party <https://www.w3.org/TR/tracking-dnt/#rep.same-party>  (array of strings representing domains) property in the JSON Tracking Status Resource. It was designed for this very  purpose, so browsers plus their extensions i.e. user agents can differentiate between domains managed by the first-party data controller from those that are not, and act accordingly.

 

It is used on the medium.com site, attached is a screen shot which shows it.

 

The TPE has been a Candidate Recommendation since last August.

 

 

Mike

 

PS I know it’s annoying it has a dash in it, but it is there and works quite well.

**Comment by catrope** [comment]
> It is used on the medium.com site, attached is a screen shot which shows it.

I think the attachment must have gotten eaten by the email-to-github-comment process. I'm guessing you meant to show that https://medium.com/.well-known/dnt/ returns:
```lang=javascript
{
  "tracking": "T",
  "policy": "https://medium.com/p/f03bf92035c9",
  "controller": "https://medium.com/policy",
  "same-party": [
    "medium.com",
    "cdn-static-1.medium.com",
    "d262ilb51hltx0.cloudfront.net"
  ],
  "config": "https://medium.com/me/settings"
}
```
(formatted for clarity, the actual response is minified)

That looks like a good way of handling this issue. A quick grep (for both `dnt` and `.well-known`) suggests that Privacy Badger currently checks for `./well-known/dnt-policy.txt` and matches it against a list of hashes, but doesn't check `./well-known/dnt`.

**Comment by michael-oneill** [comment]
There is also a “Compliance” property that can refer to non W3C compliance documents, here is ours (https://baycloud.com/.well-known/dnt) which also refers to the EFF policy. 

{

  "tracking": "N",

  "compliance": [

    "http://ec.europa.eu/justice/data-protection/article-29/documentation/opinion-recommendation/files/2012/wp194_en.pdf",

    "http://www.w3.org/TR/tracking-compliance/",

    "https://baycloud.com/.well-known/dnt-policy.txt"

  ],

  "controller": "https://baycloud.com/privacy",

  "same-party": [

    "cookieq.com",

    "cloudclinic.com",

    "donottrack.eu",

    "cookieq.eu"

  ],

  "policy": "https://cookieq.eu/privacy"

}

**Comment by DanAtkinson** [comment]
@michael-oneill Is it possible for you to modify your comments to correct/re-format them? It looks like they've become a little manged.

**Comment by michael-oneill** [comment]
OK, sorry about that. In future I will reply via github

**Comment by cooperq** [comment]
This is an interesting solution, it seems like it could be ripe for abuse though, how do we ensure that people are behaving honestly and listing same party domains in good faith? Perhaps we could crawl the alexa top 1M and use what we find to create our own list? Also some major domains haven't implemented this yet, e.g. google, wikipedia so we should probably make our own list anyway.

**Comment by michael-oneill** [comment]
It would be in companies best interests to honestly and accurately declare the domains they manage , and I think the FTC would be after them for "unfair & deceptive practices" if they did not, In Europe the DPAs can take action under data protection laws. It would be good to start the ball rolling though for the most common companies like Google, Yahoo etc,, create a JSON file as an array of default TSR objects for the most common websites (usable by PB & others until such time the sites post their own TSR) The EFF could host it, or I could suggest it to the W3C TPWG.

**Comment by catrope** [comment]
One way to curtail abuse could be to enforce reciprocity: if A's file says they are the same party as B, then verify that B's file also says they are the same party as A. Then if an evil web site wants to be clever and make doubleclick a first party, then doubleclick would have to list half the internet as a first party and their JSON file would have to be quite large :) . You could make it stricter by requiring that A's and B's first-party lists are exactly the same (i.e. they list the same C, D, E, etc.), that would make that kind of abuse even harder.

In the short term, though, I think a file within PB listing big/well-known web sites, similar to the yellow list, would be the fastest way to fix this.

(As a side note, at Wikipedia we're looking into making a software change that will eliminate these cross-domain requests entirely, so we wouldn't be directly affected any more, but this kind of behavior still affects gmail, for example.)

**Comment by michael-oneill** [comment]
Yes, that was suggested in the Working Group. I am putting together a document suggesting additions to the TPE (i.e. DNT2.0)  in light of implementation experience and that is a MAY (for user agents).

**Comment by catrope** [comment]
I just received another suggestion that could be a feasible workaround for PB while standards things are figured out: allow cross-domain requests if the two domains have the same certificate (using SubjectAltName). That wouldn't be exhaustive, but would catch some common cases and wouldn't be prone to abuse AFAICT.

**Comment by michael-oneill** [comment]
That would be great but I don't think Google gave us an API for that (looking inside certs). We could suggest it. Now Firefox uses Blink (Webextensions is working on Nightly) we could suggest it on the Mozilla list also.

It could be done by an external scanner, I will look into that.

**Comment by cooperq** [comment]
Google doesn't currently have an API for that but a patch is in the works, I'm told. So that might be a viable thing ot do in the future.

**Comment by cooperq** [comment]
from a mediawiki employee 
Privacy Badger mostly doesn't break it any more, because we worked around things by proxying through the local domain, but we forgot about POST requests.

https://blog.wikimedia.org/2016/05/12/cross-wiki-notifications/

**Comment by cooperq** [comment]
wrote some pseudo code here: https://github.com/EFForg/privacybadgerchrome/blob/master/src/multiDomainFirstParties.js
This should probably be a JSON list of arrays that gets fetched periodically from the EFF server as in the cookie block list. The rest of the logic could be added to the isThirdParty() function call.

**Comment by cowlicks** [comment]
@cooperq In your pseudo code a call to `isMultiDomainFirstParty` has  a call time that grows linearly with the size of all the domains in `multiDomainFirstPartiesArray`.

An idea:
A hashtable keyed with every domain, which maps to some value which is unique for each group of domains. Like a hash of the first party domain list. Then that hash maps to the domain list. That would give you constant checking time.

**Comment by cooperq** [comment]
The above solution would trade linear growth of call time for linear growth of memory footprint. I don't think that either of those is a desireable property. Let's keep thinking this through.

**Comment by cowlicks** [comment]
I think it would have about the same memory footprint?

**Comment by cowlicks** [comment]
I think I understand the confusion. In that PR the values of `domainLookup` are references to the arrays in `multiDomainFirstPartiesArray`. So it is basically as large as `multiDomainFirstPartiesArray`.

But if these were not references, like if we `JSON.stringifiy`'d the object it would be much larger.

**Comment by cooperq** [comment]
ah, excellent then! I think this is a good way to do this. Let's do it after we finish the web api work!
