### ISSUE TITLE
Privacy Badger site translation

### ISSUE THREAD

**Issue by victorhck** [EFForg/privacybadgerchrome#782]
Hi.

I did not find the way to help in translate Privacy Badger Site in EFF to spanish:
- https://www.eff.org//privacybadger

How can I help in that way?

Thnx

**Comment by cooperq** [comment]
@mfb should be able to explain the process (I'm not really sure).

**Comment by mfb** [comment]
Hi! It looks like we have a pull request tor this translation already: https://github.com/EFForg/www-l10n/pull/19/commits   I will see what I can do to get this translation accepted ASAP.

**Comment by victorhck** [comment]
ok!
