### ISSUE TITLE
Memory Issue on Chromium

### ISSUE THREAD

**Issue by julled** [EFForg/privacybadgerchrome#784]
Hey,

i got a serious memory issue with the privacybadger since a few months already. It seems to allocate a lot of memory within a few seconds (without opening any additional tabs/windows) until my memory +swap is full and freezes my machine. I can observe the increase of the memory in my system monitor. The increase is linear, at least at  swap where i can observe the increase. But maybe thats due to the I/O limit of my SSD.

I can not reproduce it but i often use a lot of tabs and windows. 
 
I got the following machine:
Chromium Version 48.0.2564.116
Ubuntu 16.04 (64-bit)
Badger version 2015.8.14

Any ideas?

**Comment by julled** [comment]
I will test the 2016.3.2 version of the Privacy Badger to see if the bug is still there...

**Comment by cooperq** [comment]
Is the issue still present with the latest version?

**Comment by julled** [comment]
Have not noticed it yet, but i will keep you up to date.
