### ISSUE TITLE
What's being blocked?

### ISSUE THREAD

**Issue by wumpus** [EFForg/privacybadgerchrome#790]
archive.org is showing 1 blocked cookie, which we'd like to fix. However, we can't figure out which cookie it is. Looked in the FAQ, no luck.

**Comment by cooperq** [comment]
Interesting, can you demonstrate where this is happening? I don't see any trackers blocked when I visit archive.org

**Comment by wumpus** [comment]
I see privacy badger blocking 1 thing on https://archive.org/ (red one in a square over the icon)

**Comment by wumpus** [comment]
Oh, am I mis-reading what Privacy Badger is telling me? I 1 in the red box, but when I click on the badger icon it says that it's a yellow, which isn't actually blocked.

**Comment by cooperq** [comment]
when you click the privacy badger icon what domain does it say is being blocked?

**Comment by wumpus** [comment]
There's a yellow for archive.org.

**Comment by cooperq** [comment]
wow, that definitely shouldn't be happening. Can you send me a screenshot of the behavior?

**Comment by wumpus** [comment]
![screen shot 2016-04-18 at 10 22 11 pm](https://cloud.githubusercontent.com/assets/2142266/14628553/14c305ae-05b4-11e6-9ca8-cc1072dd4a34.png)

Bright red badge, one cookie blocked, no idea which one.

**Comment by wumpus** [comment]
I did a few rounds of deleting cookies and loading with and without Privacy Badger, I don't see any cookie that is only set when Privacy Badger is off.
