### ISSUE TITLE
Privacy badger doesn't work

### ISSUE THREAD

**Issue by xros** [EFForg/privacybadgerchrome#798]
![snapshot245](https://cloud.githubusercontent.com/assets/2342412/14227023/7e2dd7e4-f925-11e5-80ad-2021087ca218.png)

it does not block any ad. installed from chrome store.

i did a upgrade days ago. and found out suddenly all ads came out....

system:  ubuntu 14.04
chrome: Version 49.0.2623.110 (64-bit)

**Comment by xros** [comment]
![snapshot246](https://cloud.githubusercontent.com/assets/2342412/14227071/a0f76348-f926-11e5-9c4c-e73b8f130fce.png)

the ad blocker did not indicate with green or red alert, not functioning

**Comment by cooperq** [comment]
if you reinstall privacy badger does it fix the problem?

**Comment by xros** [comment]
@cooperq problem solved. reinstalling privacy badger did not help. it turned out that Chrome had an important update. After upgrading chrome to the latest, it worked. 

But I still suspect that Chrome might block some HTTP requests of privacy badger fetching blacklists. 

Thing is that it works now anyway.
