### ISSUE TITLE
PB tutorial launches every time Chrome is launched

### ISSUE THREAD

**Issue by jkcohen** [EFForg/privacybadgerchrome#813]
Every time I launch Chrome, the Privacy Badger tutorial opens in its own window. I am running Chrome 50.0.2661.75 m, Privacy Badger 2016.4.13. Is there an internal setting I can use to indicate that I have already seen the tutorial?

**Comment by cooperq** [comment]
Are you using CC cleaner by any chance? See #803

**Comment by cooperq** [comment]
This should be fixed in the new version, see https://github.com/EFForg/privacybadgerchrome/wiki/Help-test-Privacy-Badger-for-chrome
