### ISSUE TITLE
Interoperability with Google "Contributor"

### ISSUE THREAD

**Issue by zv** [EFForg/privacybadgerchrome#828]
My apologies if this sort of question is not appropriate but I don't know anywhere else I can ask this.
I am currently on google "contributor", but I'm unsure of if the advertising bidding process happens such that blocking, say, "analytics.google.com" or "adwise.google.com" (and all the other domains that PrivacyBadger generally excludes) will mean that the website owner doesn't receive my "contribution".

Does running PrivacyBadger if I'm a google contributor will mean no one actually gets "paid"?

**Comment by cooperq** [comment]
Great question! I'm not really sure, this will require some research.

**Comment by cooperq** [comment]
This was the best I could find:

> For Contributor to work, your browser must be able to communicate with Google's ad servers.
>
> This means that extensions or other technologies (ad blockers or script blockers) that modify 
> browser traffic might prevent Contributor from working correctly.

So it  seems like you will need to whitelist (move to green) domains related to google advertising and doubleclick for contirbutor to work. This of course means that google still gets to track you around the web, but I guess you won't see ads from them...

**Comment by zv** [comment]
I'm feeling like I'm asking for the impossible here, but I'll try anyway.

Are there any additional headers or other identifying information sent over the wire that can be stripped?


Alternatively, has Google given any statement describing how information from DNT-sending clients is used?

**Comment by cooperq** [comment]
Not really, since you need to allow google to set third party cookies to use contributor you will need to set google ad related domains to green, which will allow them to track you. No way around it. 

Google has not made any statements regardign DNT that I am aware of.
