### ISSUE TITLE
user overrides don't propogate correctly

### ISSUE THREAD

**Issue by SwartzCr** [EFForg/privacybadgerchrome#833]
to reproduce, find a few domains that are sub domains of eachother, I used www.facebook.com, facebook.com, and connect.ak.facebook.com

When you move the top level one (etld+1), the rule propogates, but the other ones think that they're user set
Also occasionally the change doesn't stick, or it moves the others in correctly

**Comment by SwartzCr** [comment]
Similarly sometimes the user override doesn't 'stick' - so the subdomains won't propogate and then it won't remain in it's changed state once you refresh the page

so setting facebook.com won't change www.facebook.com then when you refresh facebook.com hasn't kept the override - but it works sometimes like 1/3

**Comment by cooperq** [comment]
Fixed
