### ISSUE TITLE
(cdn.)playbuzz.com

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadgerchrome#836]
https://www.answers.com/article/30990289/quiz-your-iq-is-considered-higher-than-average-if-you-can-answer-these-unusual-questions

`cdn.playbuzz.com` and `playbuzz.com` need to be moved to yellow to fix the quiz.

**Comment by cooperq** [comment]
This is a horrendous privacy policy: http://www.playbuzz.com/PrivacyPolicy

**Comment by terrorist96** [comment]
So, #400 ?

**Comment by cooperq** [comment]
I don't think that's going to fix it since playbuzz is needed to be green for the quiz to load. As in, they make the quiz. This is one that will have to be whitelisted manually.
