### ISSUE TITLE
subdomains of domains on cookie block list are being blocked

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadgerchrome#838]
http://www.nvcc.edu/
https://liberland.org/en/main/

`fonts.googleapis.com` causes the text to be larger and not as nice looking. Obvious examples include "Congratulations!" and the banner links being pushed to a second line.

https://developers.google.com/web/showcase/2016/aliexpress
Stars on the right.
https://blog.chromium.org/2016/05/the-mobile-web-is-open-for-business.html
Navigation buttons at the bottom.
https://www.algolia.com/
http://videos.howstuffworks.com/discovery/48799-animals-rare-sturgeon-key-to-breeding-program-video.htm
http://www.jobs.net/jobs/booz-allen-hamilton/en-us/job/United-States/Scientific-Research-Associate-Junior/J3K13B6D8RQXLVFJ072/
https://nikolamotor.com/one

**Comment by SwartzCr** [comment]
are you saying that it is getting blocked, or it isn't and it should?

**Comment by cooperq** [comment]
fonts.googleapis.com is being blocked even when googleapis.com is on the cookieblock list. This shouldn't be happening, looking for the cause and fix now.

**Comment by terrorist96** [comment]
What @cooperq said.

**Comment by terrorist96** [comment]
I'm just noticing how blocking fonts.googleapis can really make **a lot** of sites look uglier than they really are. Added two more examples to the OP.

**Comment by terrorist96** [comment]
^that was bothering me. :grin:
