### ISSUE TITLE
maps.googleapis.com gets blocked

### ISSUE THREAD

**Issue by SwartzCr** [EFForg/privacybadgerchrome#839]
I was using the github event submission form: https://community.github.com/sponsorships
which uses google maps to make sure you've entered a real city as an input
maps.googleapis.com was blocked by PB even though googleapis.com is on the exception list. This is a bug.

**Comment by terrorist96** [comment]
Yep, here's another example:
http://www.labsupportcareers.com/

**Comment by cooperq** [comment]
This should be fixed by #841 and in the newest release which was out this morning.
