### ISSUE TITLE
Problems with media.giphy.com on twitter.com

### ISSUE THREAD

**Issue by twuttke** [EFForg/privacybadgerchrome#852]
Hi,

twitter has a GIF search in their tweet composer. However, the images coming from these domains are blocked by Privacy Badger:
media.giphy.com
media0.giphy.com
media1.giphy.com
media2.giphy.com
media3.giphy.com
media4.giphy.com

Is there something simple twitter can do on their site to remedy this? (or why is PB blocking them?) Is it something giphy is doing on their CDN?  

Alternatively, is there a way to add these to [domain_exception_list](https://www.eff.org/files/domain_exception_list.json) for twitter.com only?

**Comment by cooperq** [comment]
fixed in abdd25c
