### ISSUE TITLE
Whitelisting is broken

### ISSUE THREAD

**Issue by ddsol** [EFForg/privacybadgerchrome#858]
YouTube doesn't work with PB enabled. It seems this is due to [recent code changes](https://github.com/EFForg/privacybadgerchrome/blob/837765033f559f2427e779785c158222c67a3197/src/webrequest.js#L86) which mistakenly were published before they were finished.

YouTube uses many subdomains, AFAICT generated, to access the video content. With just about each new video I try, another new domain is blocked and needs to be manually unblocked.

Adding `googlevideo.com` or `*.googlevideo.com` to the whitelist should allow PB to block all trackers and snoopers on YT, which are many. It does not.

This probably leads to many people disabling PB for YT, which in my opinion makes PB very ineffective, since YT for many people is a place where they spend a lot of their web time. Also, I don't believe that disabling a security feature should be a solution, and PB is a security feature. Also, it may lead to people removing PB from Chrome altogether.

**Comment by cooperq** [comment]
This should be fixed as of version 2016.5.24
