### ISSUE TITLE
Move graphiq to yellowlist

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadgerchrome#870]
http://www.foxbusiness.com/features/2016/06/15/gun-shop-owner-ar-15s-flying-off-shelves-at-500-pop.html

Move the following to yellowlist:

`w.graphiq.com`
`s.graphiq.com`
`s2.graphiq.com`
`s3.graphiq.com`

Breaks graphic at the end of article

**Comment by cooperq** [comment]
added to cookie block list. Thanks!

**Comment by terrorist96** [comment]
@cooperq can `files.graphiq.com` also be moved to yellow?
http://political-issues.insidegov.com/

**Comment by cooperq** [comment]
added, thanks!
