### ISSUE TITLE
Clef login doesn't work

### ISSUE THREAD

**Issue by cascer1** [EFForg/privacybadgerchrome#874]
Whenever I visit a site that uses [Clef](https://getclef.com), I can't login because the plugin blocks pubnub. Even when I go into the settings and whitelist pubnub.com the plugin keeps blocking the domain.

[Clef help article](http://support.getclef.com/article/112-handling-failed-websockets-connection)

**Comment by cooperq** [comment]
how are you whitelisting pubnub? are you adding it to the whitelist (which would disable pb on a tab where the first party is pubnub.com) or are you moving the slider for pubnub.com to green?

**Comment by cascer1** [comment]
I just figured out I was indeed using the wrong whitelist tool.. I figured that it would be in the whitelisted domains tab.
