### ISSUE TITLE
Compatibility with Google Maps

### ISSUE THREAD

**Issue by orschiro** [EFForg/privacybadgerchrome#875]
Dear all, 

Can we somehow make Privacy Badger fully compatible with Google Maps without excluding (whitelisting) the domain `google.com/maps`?

The features that don't work for me:

## I can't add photos to a place

![image](https://cloud.githubusercontent.com/assets/170947/16521803/b2c4f78e-3f99-11e6-977f-c3d57eada383.png)

## I can't write a review (no pop-up is being opened)

![image](https://cloud.githubusercontent.com/assets/170947/16521826/cf9871b0-3f99-11e6-84cf-cd1ef58c6070.png)

Thankfully,

~Robert

**Comment by cooperq** [comment]
I suspect that this would be best fixed by #847

**Comment by orschiro** [comment]
Thank you @cooperq!

It's great to see this being fixed soon. :+1: 

Thankfully,

~Robert
