### ISSUE TITLE
UX: User filter settings: scrollbar not fully visible

### ISSUE THREAD

**Issue by KommX** [EFForg/privacybadgerchrome#883]
In the options --> User filter settings:
The upper end of the scroll bar is invisible.

![scroll_bar](https://cloud.githubusercontent.com/assets/7859245/16983551/97525ed4-4e75-11e6-8df8-8b9e5219dc63.png)

**Comment by KommX** [comment]
Why was this issue closed?
Is it fixed in some dev version?

**Comment by ghostwords** [comment]
I think so ... Was this fixed by #947?

**Comment by cooperq** [comment]
It was actually fixed by @alexristich but I can't remember what commit it was. Will be in the next release.
