### ISSUE TITLE
userscloud issue

### ISSUE THREAD

**Issue by ghajini** [EFForg/privacybadgerchrome#886]
too much popups and tracking in this site
https://userscloud.com/x806nncpg3i6

**Comment by ghajini** [comment]
looks like developer not active involving

**Comment by alexristich** [comment]
What specifically would you like to see here? 

From what I understand, Privacy Badger is supposed to block ads from services that track you, so if the services that are delivering ads aren't using any trackers then they will be permitted. It's possible that the pesky ads on this site don't track you; if this is the case then what you might want to do is click on the extension in the menu bar and manually change the slider all the way to the left for the sites that are serving up these ads.

**Comment by cooperq** [comment]
@ghajini privacy badger only blocks things once it sees them tracking you on multiple sites. The site you linked to above is super shady. If  you are going to keep visiting sites like that you might wish to add another layer of protection to block things in addition to privacy badger.
