### ISSUE TITLE
antiadblock

### ISSUE THREAD

**Issue by ghajini** [EFForg/privacybadgerchrome#887]
how privacy badger see towards antiadblock....because on businesstoday.in with privacy badger enabled site detects as your adblocker is on though i have only privacy badger, not other adblocker
this problem is more on other sites
should i use ABP for this

**Comment by cooperq** [comment]
yep, that's because the anti adblock scripts are dumb, they only look to see if you are blocking things, and since we are blocking things we look like an adblocker. Oh well.

**Comment by ghostwords** [comment]
Related to #1596.
