### ISSUE TITLE
create a DNT compliance filter list

### ISSUE THREAD

**Issue by cooperq** [EFForg/privacybadgerchrome#894]
Should run from EFF.org and update weekly, should be compatible with ABP filter whitelists. 

Helpful copypasta: helpful copypasta: https://stackoverflow.com/questions/2632520/what-is-the-fastest-way-to-send-100-000-http-requests-in-python
Adnauseum issue: https://github.com/dhowe/AdNauseam/issues/306

**Comment by cooperq** [comment]
helpful copypasta: https://stackoverflow.com/questions/2632520/what-is-the-fastest-way-to-send-100-000-http-requests-in-python

**Comment by dhowe** [comment]
hi all, any progress on this?

**Comment by cooperq** [comment]
yes! I expect to have an announcement and something public soon.

**Comment by cooperq** [comment]
soon like this week.

**Comment by dhowe** [comment]
possible to get an early release so we can start our testing?

**Comment by cooperq** [comment]
https://www.eff.org/files/effdntlist.txt

**Comment by dhowe** [comment]
excellent, thanks

**Comment by dhowe** [comment]
A question as we do our testing:

The rules in the current list specify only 3rd party requests, e.g.,

`  @@||duckduckgo.com^$third-party`

While this works for PB, which doesn't (I believe) block 1st-party requests, 
such exception rules will not fire for cases (in list-based blockers) where a blocking or hiding rule applies to a 1st-party request

If I'm understanding this correctly, this is a real problem for list-based blockers (ABP, uBlock, AdNauseam, etc.) who want to make exceptions for domains on the DNT list...

**Comment by dhowe** [comment]
And update on this?
