### ISSUE TITLE
Request to unblock a domain

### ISSUE THREAD

**Issue by mt3o** [EFForg/privacybadgerchrome#902]
Hi, I have a domain that serves plain images from behind cloudflare. Host: xoart.link Adress to images:
http://xoart.link/$w/$h
http://xoart.link/$w/$h/$t
where:

$w=500 - width
$h=500 - height
$t=cat - tag of the picture, if omitted there will be cat in the picture.

I aimed at making this fast and lightweight. Is there anything I can do to prevent Badger blocking my domain?

**Comment by cowlicks** [comment]
Can you provide a link to a page where your domain is blocked?

**Comment by cowlicks** [comment]
@mt3o Also, you should really turn of debugging on your production server.

**Comment by mt3o** [comment]
Link is: http://www.efurgon.pl/pl/autka/54-renault-master-2-3-dci-125km-l3h2-nowy-2
However, right now, from my office pc, it works fine, xoart.link is market as green... Don't know if you changed anything or the badger changed his mind :-)

I'll later test this on other machine and give more feedback (or close the issue).

btw, yeah, debug mode should be turned off :-) maybe i'd put a cat picture there instead?

**Comment by mt3o** [comment]
It seems that now Badger likes my site. Don't know what happened, but this issue can be closed :] Thanks @cowlicks !

**Comment by cowlicks** [comment]
@mt3o I can't close this, but you can.
