### ISSUE TITLE
"Not from Chrome Web Store."

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadgerchrome#916]
I just noticed this on my extensions page. Anyone else seeing it as well?
Only PB has this noted for it. Funny thing is, I can click "Details" then "View in store" and it shows as installed with the latest version 2016.9.7

**Comment by yieldman** [comment]
I am pretty sure 2016.8.29 is the latest version. Are you sure you have installed it from google web store??

**Comment by terrorist96** [comment]
![1](https://cloud.githubusercontent.com/assets/12802056/18354274/ef637824-75b2-11e6-85da-c340898e30a3.PNG)

**Comment by yieldman** [comment]
This is the line giving us the trouble:-

https://cs.chromium.org/chromium/src/chrome/browser/extensions/api/developer_private/extension_info_generator.cc?q=IDS_OPTIONS_INSTALL_LOCATION_UNKNOWN&sq=package:chromium&dr=C&l=455

reference file:-

https://cs.chromium.org/chromium/src/chrome/app/generated_resources.grd?q=%22Not+from+Chrome+Web+Store%22&sq=package:chromium&dr=C&l=9858

**Comment by yieldman** [comment]
https://github.com/EFForg/privacybadgerchrome/commit/9a5535274f098f66c87a43c3b6e3d51ba4b5efa2

This commit probably fixes this. Can you test this @terrorist96 ?

**Comment by terrorist96** [comment]
I haven't seen a new version pushed to the Chrome Web Store yet, so I can't say for sure if it's been fixed yet.

**Comment by cooperq** [comment]
Hey sorry everyone for the confusion, this is indeed because I removed the update URL from the generated crx file to try to fix #885. It didn't work. I have readded it as @yieldman noticed and it will be fixed in the next release. Nothing to worry about in the meanwhile.
