### ISSUE TITLE
Javascript Error line 291 in socialwidgets.js

### ISSUE THREAD

**Issue by stephaniehobson** [EFForg/privacybadgerchrome#920]
> Error in event handler for runtime.onMessage: Type error: Cannot read property forEach of undefined.

Seems like the check on line 290 for `null` is not catching cases where the value is `undefined`. Depending on what's being passed in here a check for length might be more precise? 

I had a quick look to see if I could submit a PR instead of an Issue but I don't understand the code well enough.

I had a Chrome extension which was injecting some malicious code and Privacy Badger was blocking it 🎉  but then not able to find what it was expecting in the DOM of the website. A large portion of out site users have the same problem - I discovered it by trolling the javascript errors on our site. (I'm primarily a Firefox user myself).

**Comment by cooperq** [comment]
Thanks for the bug report! I will look into this!

**Comment by Sim-fff** [comment]
![default](https://cloud.githubusercontent.com/assets/22250832/18801522/c8d4dfe6-81eb-11e6-941f-bd89c05d15c6.jpg)
