### ISSUE TITLE
Chromium 54 hangs with "Waiting for extension Privacy Badger"

### ISSUE THREAD

**Issue by whitslack** [EFForg/privacybadgerchrome#922]
Attempting to load any web page, including the default "New Tab" page, hangs as of Chromium 54.0.2840.16 (on Gentoo Linux), with a status message, "Waiting for extension Privacy Badger."

Uninstalling the extension and reinstalling it seems to resolve the issue, as does wiping out the directory `~/.config/chromium/Default/Local Extension Settings/pkehgijcmpdhfbdbbnkijodmdjhbjlgp`. However, these are unacceptable, as they cause the entire history of trackers and overrides to be lost.

Downgrading to Chromium 53.0.2785.101 also restores proper functionality.

While Privacy Badger is hanging, no sources appear in the background page inspector that is accessible via Developer Mode on the chrome://extensions page. (Sources appear properly in the inspector on Chromium 53.)

Possibly this is a Chromium bug, but it seems odd that blowing away the extension's settings directory allows it to work on Chromium 54, so maybe there has been an API change that Privacy Badger needs to accommodate?

**Comment by cooperq** [comment]
This is very strange. What version of privacy badger do you have? Now that you have reinstalled are you able to reproduce the issue at all?

**Comment by whitslack** [comment]
I made a backup of my entire `~/.config/chromium` tree, so yes, I can reproduce the issue at will. I have downgraded to Chromium 53 for now, but I can easily switch between 53 and 54 if there are any information-gathering tasks you'd like me to perform.

**Comment by cooperq** [comment]
Yes, can you please do the following
1. go to chrome://extensions
2. click the box to enable developer mode
3. click 'inspect background page' underneath privacy badger
4. click the profiles tab -> profile cpu -> start
5. browse around for a while until you get 'waiting for privacy badger' a few times
6. click 'save' next to the profile you made and send it to me

Thanks!

**Comment by whitslack** [comment]
@cooperq: This doesn't work. I can start profiling, but when I stop profiling, there is no option to save the profile. Under "Profile 1" in the list of "CPU PROFILES", it still says "Recording…". And I cannot start profiling again, as the "Start" button is disabled. In fact, I can't even switch to another tab in the Inspector window at this point. I don't think Chromium is fully loading the extension, as the Sources tab (which I can view if I haven't tried to start profiling) shows no sources.

**Comment by whitslack** [comment]
This misbehavior must have been caused by a bug in Chromium 54.0.2840.16. I have upgraded to 54.0.2840.27, and Privacy Badger is working fine.

**Comment by cooperq** [comment]
Great! Glad to hear it!
