### ISSUE TITLE
after re-installation, nothing is being blocked

### ISSUE THREAD

**Issue by chip-rosenthal** [EFForg/privacybadgerchrome#925]
I encountered the corrupt extension problem reported elsewhere (issue 911)

I removed and reinstalled Privacy Badger, and the error is cleared. Except now nothing is being blocked.

![image](https://cloud.githubusercontent.com/assets/1208924/18496268/398d06aa-79ea-11e6-9204-3caa5d221ae1.png)

This is:
- Privacy Badger 2016.9.7
- Google Chrome for Linux, Version 54.0.2840.16 beta (64-bit)

**Comment by alexristich** [comment]
When you uninstall an extension, I believe it also clears any local information stored by that extension. In Privacy Badger's case, this unfortunately means the dynamic database of trackers it has built up during usage. As you browse, the database will begin populating again with websites that the heuristic has determined are trackers.

@cooperq mentioned in #911 that the issue with the "corrupt extension" issue should be fixed in the next version.

Unfortunately not great news, though the database should be built up again pretty quickly!

**Comment by chip-rosenthal** [comment]
I clicked around to a couple dozen sites that presumably have tracking cookies for just this purpose, but nothing was ever registered. I'd think unless there is some high threshold to cross before a site is marked bad, it should have recorded something.

**Comment by alexristich** [comment]
Hmm, that's strange... Privacy Badger should block a tracker once it detects it on three different domains.
Just to be sure, I deleted the extension and reinstalled it and visited these three sites, in this order:
www.macrumors.com
www.theglobeandmail.com
www.nytimes.com

Once the page for www.nytimes.com loaded, Privacy Badger showed 8 separate trackers as having been blocked. Would you try visiting these sites in this order and see if the number displayed in the icon is _at least_ 8?

**Comment by chip-rosenthal** [comment]
I'm wondering if I'm seeing an interaction between Privacy Badger and Ublock Origin?

I ran this test twice. First with Ublock Origin enabled.

When complete, the only tracker blocked was cdn.optimizely.com.

I disabled Ublock Origin, tried all three links again (shift-reload), and now 5 of 13 potential trackers are blocked.

￼￼￼￼

**Comment by alexristich** [comment]
That could certainly be it. It's possible that uBlock Origin is filtering the trackers before Privacy Badger gets to them. I don't have a huge amount of experience with uBlock Origin, so I don't know how well it plays together with Privacy Badger. If it is the case that uBlock Origin is capturing and blocking requests before Privacy Badger analyzes and blocks them, it _is_ possible that Privacy Badger isn't analyzing the requests and looking for tracking behaviors at all, and thus not building up a dynamic database of trackers, though your experience can probably qualify this better.

**Comment by cooperq** [comment]
This is definitely because ublock is blocking the trackers before privacy badger gets a chance to see that they are tracking you. TBH this is fine because it means that the trackers are being blocked! Ublock and privacy badger compliment each other very well IMO.

**Comment by chip-rosenthal** [comment]
Thanks @alexristich and @cooperq for the feedback on this issue.

**Comment by alexristich** [comment]
@chip-rosenthal Happy to help!
