### ISSUE TITLE
*.wpengine.com breaks site

### ISSUE THREAD

**Issue by terrorist96** [EFForg/privacybadgerchrome#950]
https://www.topcoder.com/

`wwwtc.wpengine.com` needs to be moved to yellow.

**Comment by terrorist96** [comment]
http://digitalcurrency.unic.ac.cy/about-the-program/

`dcurrency.wpengine.com`

**Comment by cooperq** [comment]
added, thanks!

**Comment by terrorist96** [comment]
http://www.dealeron.com/

`dealeroncorp.wpengine.com`

This should probably be fixed in the next update as well then.
