### ISSUE TITLE
page broken by privacy badger

### ISSUE THREAD

**Issue by ghajini** [EFForg/privacybadgerchrome#956]
see screenshot
how to overcome this
![screenshot 44](https://cloud.githubusercontent.com/assets/20338483/19161530/cf899086-8c11-11e6-9219-8a5fd8476dc3.png)

**Comment by alexristich** [comment]
Hi! It looks like you can fix this by opening the Privacy Badger menu (click on the extension in the menu bar) and moving the slider for "graph.facebook.com" to yellow.

(@cooperq, should we throw Facebook into the cookieblock list or no?)

**Comment by cooperq** [comment]
Nope, we should not cookieblock this. Moving it seems to work for now.
