### ISSUE TITLE
canvas fingerprint

### ISSUE THREAD

**Issue by Helpper** [EFForg/privacybadgerchrome#981]
I have a question. Can it block canvas fingerprint?

**Comment by alexristich** [comment]
@cooperq and @ghostwords have a better understanding of this, so they can chime in if I'm mistaken on this.

My understanding is that Privacy Badger currently detects canvas fingerprinting, and uses this as one part of its tracker detection algorithm. It doesn't currently block first-party canvas fingerprinting. Once Privacy Badger has determined a third-party is a tracker, then access to that tracker will be blocked entirely; this will prevent any and all fingerprinting.

That being said, being able to block both first- and third-party fingerprinting would be awesome, and, provided it worked well, would certainly be a welcomed feature.

**Comment by Helpper** [comment]
Thank you for your explanation.

**Comment by alexristich** [comment]
Happy to help! I'll close this issue, and the others can post if any clarification or correction is needed on my comment above.

If you have any other questions or issues feel free to open up another issue.
